ericniebler/range-v3

include/range/v3/algorithm/for_each.hpp

Template parameters V and X seem to be no longer used, since their former use is nowadays pushed into IndirectInvokable concept.

Removing unused template parameters from for_each

---

include/range/v3/utility/meta.hpp

- \brief is not necessary for Doxygen comments.
- Add std::deque specialization to libcxx workarounds.
- Add complexity sections + LaTeX.
- Use \p to denote metafunction parameters.

Documentation changes from meta repository

---

include/range/v3/utility/basic_iterator.hpp

No behavior is affected by this patch, this pr just makes the currently defaulted implicitly-declared copy constructor explicitly-declared instead. 
AFAIK `basic_iterator` will be rewritten "soon" anyways.

add explicit defaulted copy constructor to proxy

---

include/range/v3/detail/config.hpp

Defining the macro `RANGES_DISABLE_DEPRECATED_WARNINGS` allows disabling all deprecated warnings from range-v3.

Add macro to disable all deprecated warnings

---

include/range/v3/view/join.hpp

Missing include in join.hpp:
```c++
#include <range/v3/view/join.hpp>
int main() {}
```
yields
```bash
crookston@crookston:~$ clang++-3.5 simple.cpp -I dev/range-v3/include/ -std=c++11
In file included from simple.cpp:1:
dev/range-v3/include/range/v3/view/join.hpp:282:30: error: no member named
'empty' in namespace 'ranges'
(ranges::empty(this->mutable_base()) ? 0 :
~~~~~~~~^
1 error generated.
```
Thanks for this library!

Add missing include: empty.hpp

---

include/range/v3/view/take_while.hpp
test/view/take_while.cpp

A const sentinel of `view::take_while` required a const predicate and a const range. 
Was that intended? (See new tests).

fix take_while sentinel constraint

---

include/range/v3/at.hpp
include/range/v3/back.hpp
include/range/v3/begin_end.hpp
include/range/v3/empty.hpp
include/range/v3/front.hpp
include/range/v3/range_access.hpp
include/range/v3/range_fwd.hpp
include/range/v3/size.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/swap.hpp
test/CMakeLists.txt
test/array.hpp
test/constexpr_core.cpp
test/test_iterators.hpp
test/utility/CMakeLists.txt
test/utility/reverse_iterator.cpp
test/utility/swap.cpp
test/view/CMakeLists.txt

- adds constexpr to:
- begin, end, rbegin, rend, cbegin, cend, crbegin, crend
- note: i've hijacked ADL for C-arrays and initializer lists in ranges::rbegin/rend/crbegin/crend 
because std::rbegin/rend/crbegin/crend are not constexpr (while std::begin/std::end are...). 
- a constexpr reverse_iterator is added to utility to make this work.
- advance, next, prev, distance, iter_size, swap, indirect_swap
- note 1: i've hijacked std::advance for pointers since it is not constexpr
- note 2: for the test iterators I have to define advance overloads that forward
to range-v3 ones. I think it would be better to allow customizing advance's implementation
via a different name (e.g. advance_customization_point), and not import std::advance at all. 
- front, back, empty, size, at
- adds constexpr …

enable relaxed constexpr in core

---

perf/CMakeLists.txt
perf/sort_patterns.cpp

problem: perf/sort_patterns requires c++14 and breaks in travis under C++11.
solution: disable sort_patterns in C++11 
I'll clean sort_patterns and backport it to C++11 later on.

disable sort_patterns in cxx11

---

include/range/v3/action/concepts.hpp

* Comma overload protection for the void expression requirements
* Require InputIterator for ReserveAndAssignable
* Don't bother with a concept for RandomAccessReservable, a meta::fast_and suffices

Tidy the Reservable concepts

---

perf/counted_insertion_sort.cpp
test/action/sort.cpp
test/action/unique.cpp
test/algorithm/inplace_merge.cpp
test/algorithm/make_heap.cpp
test/algorithm/max_element.cpp
test/algorithm/min_element.cpp
test/algorithm/minmax_element.cpp
test/algorithm/nth_element.cpp
test/algorithm/partial_sort.cpp
test/algorithm/partial_sort_copy.cpp
test/algorithm/pop_heap.cpp
test/algorithm/push_heap.cpp
test/algorithm/sort.cpp
test/algorithm/sort_heap.cpp
test/algorithm/stable_sort.cpp

including use of ranges::random_shuffle and std::random_shuffle
except for definition and unit tests for ranges::random_shuffle
include <random> in make_heap.cpp
include <random> in min_element.cpp

(was #158) replace deprecated random_shuffle with shuffle

---

include/range/v3/range_concepts.hpp

Comments that were missed in the "Great Renaming."

Correct two instances of "range" to "view" in comments.

---

include/range/v3/range_traits.hpp

Not a functional change, simply uses a different access path to the same entities for documentation purposes. I.e., to make it clear that the range traits don't depend on View concepts.

Get range trait definitions from Range, not View.

---

include/range/v3/numeric/adjacent_difference.hpp
include/range/v3/numeric/partial_sum.hpp
include/range/v3/utility/concepts.hpp

All three of these mis-apply a constraint to what may be an lvalue reference type which they actually intend to apply to the underlying value type.

Fix reference type bugs in Function, AdjacentDifferentiable, and PartialSummable

---

include/range/v3/action/concepts.hpp
include/range/v3/numeric/accumulate.hpp
include/range/v3/numeric/adjacent_difference.hpp
include/range/v3/numeric/inner_product.hpp
include/range/v3/numeric/partial_sum.hpp
include/range/v3/range.hpp
include/range/v3/utility/common_tuple.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/iterator.hpp
test/utility/concepts.cpp

As discussed in ericniebler/stl2#10.
Note that `ConstructibleRef` is a positively terrible name for "Constructible object or reference type."
Also, I'm not convinced that `CopyConstructible<Foo> && Movable<Foo>` is a meaningful constraint for algorithms that want to memoize the return value of a projection a la adjacent_difference. I can't imagine there are many useful types that are copy constructible and move assignable but not copy assignable - I don't think there would be anything lost by simply requiring `Copyable`.

Update Concepts for decomposition design

---

CMakeLists.txt
include/range/v3/action/join.hpp
include/range/v3/action/split.hpp
include/range/v3/at.hpp
include/range/v3/to_container.hpp
include/range/v3/utility/compressed_tuple.hpp
include/range/v3/utility/get.hpp
include/range/v3/utility/integer_sequence.hpp
include/range/v3/utility/meta.hpp
include/range/v3/view/generate_n.hpp
include/range/v3/view/take.hpp
include/range/v3/view/transform.hpp
include/range/v3/view_interface.hpp
test/CMakeLists.txt

All kudos go to Louis Dione for writing the CMake scripts of Boost.Hana. 
This just adapts his scripts for range-v3; all mistakes introduced are only mine.
- fix missing includes caught by the tests.
- replace `# warning` with `#pragma message` because `-Werror, -Wpedantic` complains that 
`# warning` is a language extension (this prevents some new tests from compiling).
Closes #182  .

fix missing includes forever

---

include/range/v3/utility/optional.hpp
include/range/v3/utility/variant.hpp

`tagged_variant` constructors and `set` are now variadic. Note that the variadic implementation of `construct_fun` is an egregious hack with `const_cast` since the visitation implementation wants visitors to be immutable, but I want to perfect forward the constructor arguments.
Drive-by: reduce redundant code by using a common implementation for `tagged_variant` move/copy constructor/assignment, and another for detail::variant_data copy/move.
Drive-by: Remove unnecessary `operator!` from optional.

tagged_variant default constructs the first alternative if possible.

---

CMakeLists.txt

All kudos go to Louis Dione for writing the CMake scripts of Boost.Hana.
This just adapts his scripts for range-v3; all mistakes introduced are only mine.
- fix missing includes caught by the tests.
- replace # warning with `#pragma message` because `-Werror, -Wpedantic` complains that  `# warning` is a language extension (this prevents some new tests from compiling).
Thanks @tamaskenez for the fix described in #184 .

fix missing includes forever v2

---

include/range/v3/range_fwd.hpp
include/range/v3/view/cycle.hpp
test/view/CMakeLists.txt
test/view/cycle.cpp

Turns a finite `ForwardRange` into an infinite range that cycles on itself. 
```c++
auto il = {0, 1, 2};
RANGES_FOR(auto i, il | view::cycle) { std::cout << i << " "; }
```
prints "0 1 2 0 1 2 0 1 2 0 1 2...". 
This designs chooses to make two iterators compare equal only if they point to the same element of the sequence within the same cycle. Example: in the sequence above both iterators `begin` and `begin  + 3` point to the same element (`0`); since they are "in different cycles" they are not equal. 
The rationale is that this allows iterating from `[begin, begin + M)` where `M` is larger than the number of elements in the sequence.
- The implementation of `cycled_view<Rng>::cursor<IsConst>::advance` is pretty ugly.
- The implementation of `cycled_view<Rng>::cursor` can be optimized for …

view::cycle

---

include/range/v3/view/group_by.hpp
include/range/v3/view/split.hpp
test/view/group_by.cpp
test/view/split.cpp

Some views mutate its state on begin/end (e.g. `view::remove_if` on begin).  
This patch constrains `view::group_by` and `view::split` `begin_cursor` on `Range<const Rng>()`
to disable the const overload for these kinds of ranges (such that the non-const overload
is picked up instead).

bugfix: group_by and split broken for mutable views

---

example/recursive_range.hpp
include/range/v3/action/drop.hpp
include/range/v3/action/drop_while.hpp
include/range/v3/action/erase.hpp
include/range/v3/action/remove_if.hpp
include/range/v3/action/shuffle.hpp
include/range/v3/action/slice.hpp
include/range/v3/action/split.hpp
include/range/v3/action/stride.hpp
include/range/v3/action/take.hpp
include/range/v3/action/take_while.hpp
include/range/v3/action/unique.hpp
include/range/v3/algorithm/shuffle.hpp
include/range/v3/range.hpp
include/range/v3/range_concepts.hpp
include/range/v3/to_container.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/common_iterator.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/iterator_concepts.hpp
include/range/v3/view/intersperse.hpp
include/range/v3/view/partial_sum.hpp
include/range/v3/view/split.hpp
include/range/v3/view/transform.hpp
include/range/v3/view/zip_with.hpp
include/range/v3/view_interface.hpp
test/utility/basic_iterator.cpp
test/view/zip.cpp

* Use `std::declval` instead of `ranges::concepts::val` in `Swappable`.
* Variadic `Same` (This is an extension; I'm sure we'll put it in the spec eventually.)
* Rename `Derived` to `DerivedFrom`.
Drive-by: Replace several instances of tests for "single pass"-ness:
```
Derived<input_iterator_tag, Foo>
```
with uses of `SinglePass` so that an input iterator tagged with
```
struct my_input_iterator_tag : input_iterator_tag {}
```
is appropriately single-pass.
* `Convertible` changes:
* Rename `Convertible` to `ImplicitlyConvertibleTo`
* Add `ExplicitlyConvertibleTo`
* Add `ConvertibleTo` that subsumes both `ImplicitlyConvertibleTo` and `ExplicitlyConvertibleTo`.
This is half extension as well, but almost certainly required to specify the library. I don't think generic code should have to …

Update core concepts to spec as of the current Ranges proposal:

---

include/range/v3/utility/swap.hpp

`Swappable` doesn't care about the return type of `swap`. Hmmm.... the ranges proposal requires `swap(...)` to be equality preserving. That needs to be `(void)swap(...)` since we don't care about the return value.

In is_swappable, don't require swap to return void

---

include/range/v3/action/insert.hpp

SizedIteratorRange doesn't necessarily imply SizedRange, and vice versa.

Fix requirements for container reservation in action/insert:

---

include/range/v3/algorithm/search.hpp
include/range/v3/algorithm/search_n.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/iterator.hpp

* Implement `make_counted_iterator` from the ranges proposal
* Remove the remaining vestiges of `recounted(Iterator, Iterator)` that was removed from `counted_iterator` to support cyclic iterators in ce2d726e.
* Remove the `search` and `search_n` implementations for sized ranges of `RandomAccessIterator`. Without `recounted(I, I)`, they are no more efficient than the general sized range implementation.

counted_iterator-related changes:

---

include/range/v3/range_concepts.hpp

i.e., `range_iterator_t` is `decltype(begin(declval<T&>()))` and `range_sentinel_t` is `decltype(end(declval<T&>()))`. This fixes a compile error in test/view/transform.cpp with clang-3.4 that happens only on my Ubuntu install, and not on Travis for whatever reason:
```c++
auto && rng2 = rgp | view::transform(&std::pair<int,int>::first);
has_type<int &>(*begin(rng2));
CONCEPT_ASSERT(Same<range_value_t<decltype(rng2)>, int>());
```
clang refuses to resolve `decltype(begin(val<decltype(rng2)>()))` inside `range_value_t` here, as it should since `begin` on rvalues is a terrible idea ;)

Update range_iterator/sentinel_t to the Ranges proposal.

---

.travis.yml

This should fix travis-ci build-issues as in https://travis-ci.org/ericniebler/range-v3/jobs/82473863.

Fix travis-ci builds for clang-3.7

---

README.md
include/meta/meta.hpp
include/meta/meta_fwd.hpp
test/CMakeLists.txt
test/constexpr_core.cpp

Disable constexpr_core since it's ill-formed. E.g., `ranges::begin` isn't `constexpr`, this test cannot possibly complete with -std=c++14. I assume the test is abandoned.
Also disables the flags in test/CMakeLists.txt to force static linking and debug info.
Fixes #210.

Update to current meta; update compiler support matrix in README.

---

doc/index.md

It looks like this example meant to use repeat_n instead of repeat.

Fix example to use repeat_n

---

include/range/v3/view/iota.hpp
test/view/iota.cpp

iota_minus was implemented as `(D)(v0 - v1)`, where `D` is the
`iota_difference_t` of the `UnsignedIntegral` type of `v0` and `v1`.
Example: `v0 = 0`, and `v1 = 1` causes iota_minus to overflow.
Note: this overflow is perfectly defined behavior, but the result is
not what the users of iota_minus expect.
`v0 < v1? - static_cast<D>(v1 - v0) : static_cast<D>(v0 - v1);`
That is, we check which integer is larger, we perform a non-overflowing
subtraction using the current type, and then we cast to the difference
type and correct the sign.
Pros: it maximizes the range for which iota_minus works correctly
without overflowing.
Cons: it introduces a branch and a signed bit change.
`static_cast<D>(v0) - static_cast<D>(v1)`
That is, we truncate the `UnsignedInteger`s into the different type and
then …

[bugfix] view::iota_minus overflow for UnsignedIntegral

---

include/range/v3/algorithm/permutation.hpp

I just found this terrible error in cmcstl2, and realizing that `is_permutation` came from range-v3 I figured it should be fixed here as well.

Correct critical error in is_permutation

---

include/range/v3/utility/variant.hpp

G++ 4.9 doesn't like:
```c++
template<typename T, typename U>
auto operator()(T &&t, U &&) const ->
decltype(fn()(std::forward<T>(t)))
{
return fn()(std::forward<T>(t));
}
```
In the new variant code when `fn` is a non-static-member function. This patch changes that syntax in several places to:
```c++
template<typename T, typename U>
auto operator()(T &&t, U &&) const
RANGES_DECLTYPE_AUTO_RETURN
(
this->fn()(std::forward<T>(t))
)
```
which 4.9 strangely enough *does* accept.

Make GCC 4.9 happy with variant

---

include/range/v3/to_container.hpp

Fixes #240 by not using uniform initialization in `to_container` when initializing a container from an iterator range.

To container fix

---

include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/common_iterator.hpp

`basic_iterator` currently exposes its cursor though the public member function `get` in `basic_mixin`. Given that `get` is an incredibly common function name, there is a fair likelihood that someone will mistakenly use `i.get()` when they meant `i->get()` or `(*i).get()`. This patch makes `basic_mixin::get` a `protected` member, and officially blesses `get_cursor` as the approved way to break encapsulation and retrieve a cursor from a `basic_iterator`.

Protect basic_mixin::get to avoid inadvertent access

---

include/range/v3/utility/box.hpp

Commit 6bddf650d9b53197bb82a504e8038a160b56174c uses `std::is_final` if C++>11, which breaks e.g. when clang is used with libstdc++-4.9 in C++14 mode.
This commit also checks if the std library implementation is libstdc++, and in that case, if its version is >= 5.1, which implements std::is_final according to their docs (haven't tested this though).

libstdc++<5.1 doesn't provide std::is_final

---

include/range/v3/utility/iterator.hpp
include/range/v3/utility/iterator_concepts.hpp

* Coalesce the two `SizedIteratorRange` overloads of `advance_fn::bounded_`.
* Remove a couple of unnecessary casts of (sentinel - iterator) to
`iterator_difference_t<iterator>`.
* `Incrementable` requires `EqualityComparable`; `ForwardIterator` need not
require it directly (even in a comment).

Minor cleanup of Pull#264:

---

include/range/v3/view/transform.hpp

Fix iter_transform2_view::cursor constructor to take range_iterator_t<Rng1> and range_iterator_t<Rng2> instead of twice range_iterator_t<Rng2>.

fix iterator type in iter_transform2_view::cursor constructor

---

include/range/v3/utility/basic_iterator.hpp
include/range/v3/view/view.hpp

Corrects a cause of major breakage when __GNUC__ is not defined, including DevDiv 191705. Changing the trigger for the GCC PR 60799 workaround from `#ifndef __GNUC__` to `#if !defined(__GNUC__) || defined(__clang__)` disables the workaround when compiling with clang, which should prevent this issue from reccurring.

basic_sentinel's constructors must be public.

---

.travis.yml

* Enable GCC5 C++11 ASAN in the test matrix. (GCC doesn't support
-fsanitize=integer)
* Fix typo in .travis.yaml that was effectively disabling sanitzers
for ASAN builds
* **Intentionally** disable ASAN for clang; it's broken on Travis pending resolution
of https://llvm.org/bugs/show_bug.cgi?id=22757.
Relates to #206.

Travis updates:

---

include/range/v3/size.hpp

Avoids ambiguous lookup for `size(a)` when `std::size(T(&)[N])` is defined and `std` is an associated namespace of `T`.

size: grab array types before std::size sees them to avoid ambiguity.

---

CMakeLists.txt
test/view/chunk.cpp
test/view/stride.cpp

* Force C++14. Parts of the standard library need C++14 to compile.
* Don't validate complete EBO for some range iterators, the MS ABI allows only limited EBO.
* Tell clang not to blow up the build simply because `__GNUC__` is undefined.

Minor cleanups to help Clang/C2 compiles:

---

CMakeLists.txt

Is this is what commit d85d1ad7b860e8175448378adc5a23327c6eadd7 meant?
Right now the library installs to `${CMAKE_INSTALL_PREFIX}/install`. I think it should install to `${CMAKE_INSTALL_PREFIX}/include`.

fix cmake install target

---

include/range/v3/view/set_algorithm.hpp
test/view/set_symmetric_difference.cpp
test/view/set_union.cpp

In case of lazy set union and symmetric difference views, comparing iterators for equality must involve subiterators of both operand ranges. Fixes bug where it1_ has already reached the end (and is therefore not incremented anymore) but it2_ still provides new elements.

fix equal() for set_union_cursor and set_symmetric_difference_cursor

---

.travis.yml

...with working sanitizers!
Specifically: adds clang 3.8 configs with C++11/14, Debug/Release, ASAN=On only.

Add clang 3.8 to the test matrix.

---

include/range/v3/view/intersperse.hpp

...for obvious reasons, and so that the correctness of the view doesn't depend on `sentinel_adaptor` being empty & trivial to trigger the `compressed_pair` optimization.

intersperse_view::sentinel_adaptor::empty should be const

---

include/range/v3/detail/config.hpp
test/view/chunk.cpp
test/view/stride.cpp

Instead of trying to determine from the preprocessor if we're on a platform with broken EBO, detect directly if EBO is broken.

Give up on preprocessor macros: actually test for broken EBO.

---

include/range/v3/range_access.hpp
include/range/v3/utility/basic_iterator.hpp

* Add perfect-forwarding accessors for `basic_iterator::pos()` and `basic_sentinel::end()` to `range_access`.
* Remove fine-grained friend relationships for `basic_sentinel` and `basic_iterator`; all access is now via `range_access`.
* `get_cursor_fn::operator(basic_iterator&&)` doesn't *copy* the cursor, it *moves*.

Permanently workaround CWG1699 aka GCC PR60799:

---

.travis.yml

It often runs over the Travis-mandated 50 minute per-job time limit.

Disable GCC5 Release+ASAN config

---

include/range/v3/range_concepts.hpp
include/range/v3/size.hpp

* Prefer member to non-member size
* Ensure that size always returns an `Integral`

[size] Update to TS spec:

---

.travis.yml
include/range/v3/range_fwd.hpp
include/range/v3/utility/box.hpp

Instead of checking for clang this checks for libc++.

fix libstdcxx4.9 support and test clang+libstdc++ on travis (C++11 only)

---

include/range/v3/view/generate_n.hpp
include/range/v3/view/join.hpp
test/view/join.cpp

* BUGFIX: Don't rely on value-initialized **input** iterators comparing equal.
* BUGFIX: Don't use accumulate() to calculate size() if the underlying range is not Forward.
* Use default_sentinel, avoid view_adaptor.

view::join rework

---

include/range/v3/utility/common_tuple.hpp
test/utility/common_type.cpp

common_foo, common_foo => common_foo
common_foo, std::foo => common_foo if there are member references, otherwise std::foo
Fixes #367.

Saner rules for common_type/common_reference of common_foo and std::foo.

---

include/range/v3/view/set_algorithm.hpp
include/range/v3/view/transform.hpp
include/range/v3/view/zip_with.hpp

These cursors implement `indirect_move` as a friend function of their `basic_iterator`s and must perform heroic measures to workaround the gcc friend name injection bug. Current design intent is to implement a `move()` member in the cursor type and let `basic_iterator` handle the rest.

Implement move() in cursors for set_algorithm, transform, and zip views

---

include/range/v3/detail/config.hpp
range-v3.vcxproj
range-v3.vcxproj.filters
test/CMakeLists.txt
test/config.cpp

...which went unnoticed because `RANGES_DEPRECATED` is currently unused. Added a test to avoid regression.
Alternatively, we could simply get rid of `RANGES_DEPRECATED`. I chose not to do so in the expectation that we'll need it again in the not-so-distant future.

Workaround warnings when using RANGES_DEPRECATED with -std=c++11

---

doc/index.md
example/calendar.cpp
include/range/v3/range_access.hpp
include/range/v3/view/adjacent_filter.hpp
include/range/v3/view/adjacent_remove_if.hpp
include/range/v3/view/chunk.hpp
include/range/v3/view/const.hpp
include/range/v3/view/delimit.hpp
include/range/v3/view/drop_while.hpp
include/range/v3/view/indirect.hpp
include/range/v3/view/intersperse.hpp
include/range/v3/view/move.hpp
include/range/v3/view/partial_sum.hpp
include/range/v3/view/remove_if.hpp
include/range/v3/view/reverse.hpp
include/range/v3/view/stride.hpp
include/range/v3/view/take_while.hpp
include/range/v3/view/transform.hpp
include/range/v3/view_adaptor.hpp
include/range/v3/view_interface.hpp
test/view_adaptor.cpp

Both the alias template and the `view_adaptor` member of the same name.
While doing so, I noticed that `view_interface` and `view_facade` have public destructors which could be made private to reduce the danger of polymorphically deleting a class derived from either/both.
The compiler then complained about `drop_while_view`'s copy constructor failing to copy its `view_interface` base, causing me to notice that `drop_while_view` has mutually exclusive predicate and iterator members that should be stored in a variant.

Eliminate `view_adaptor_t`

---

CMakeLists.txt

[CMakeLists] No need to avoid checking re_enable_warnings.hpp, it's gone

---

include/range/v3/utility/common_iterator.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/move.hpp
include/range/v3/view/join.hpp
include/range/v3/view_adaptor.hpp

* `common_iterator`, `counted_iterator`, `reverse_iterator`, `move_iterator`, `move_into_iterator`, `adaptor_cursor`.
* Simplify `indirect_move`
* Properly name `view::join`'s move member `move` instead of `indirect_move`

Remaining friend-to-cursor indirect_move changes

---

test/algorithm/set_difference.hpp
test/algorithm/set_intersection.hpp
test/algorithm/set_symmetric_difference.hpp
test/algorithm/set_union.hpp

A certain compiler warns about comparing `bool` with literal `0`.

Don't compare bool with 0 in set algorithm tests

---

include/range/v3/getlines.hpp
include/range/v3/istream_range.hpp
test/getlines.cpp
test/view/zip.cpp

`istream` and `getlines` are poster children for mutable input ranges: Why copy elements/lines from the input range when we can move them out?

Mutable istream_range / getlines_range

---

.travis.yml

* Disable non-OSX clang builds; LLVM APT repo is broken.
* Disable GCC5 ASAN build - Ubuntu managed to break ASAN in gcc 5.4.

Travis build fixes:

---

include/range/v3/detail/config.hpp
include/range/v3/iterator_range.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/box.hpp
include/range/v3/utility/compressed_pair.hpp
include/range/v3/utility/functional.hpp
include/range/v3/utility/tagged_pair.hpp
include/range/v3/utility/tagged_tuple.hpp
include/range/v3/view/chunk.hpp
include/range/v3/view/replace_if.hpp
include/range/v3/view/stride.hpp
include/range/v3/view_adaptor.hpp
test/iterator_range.cpp
test/utility/basic_iterator.cpp
test/view_adaptor.cpp

`compressed_pair`:
* Implement `compressed_pair`'s notion that multiple empty+trivial objects can be coalesced into a single object in `box`. Guard `box`'s EBO specialization against types that could be lambda closures when the compiler is GCC 6+.
* Implement `compressed_tuple` as a simple aggregation of `box`es.
* `compressed_pair` becomes essentially `tagged<compressed_tuple<tag::first(First), tag::second(Second)>`; all `.first` and `.second` member references become `.first()` and `.second()`.
* Replace `iterator_range`'s `tagged_pair` base with `tagged_compressed_tuple`.
* Replace `replacer_if_fn`'s `compressed_pair` member with a base.
`tagged` refactoring:
* Ensure that `tagged's conversions are only used for conversion.
* Construct by getter chain inheritance instead of fan …

Refactor compressed_pair and tagged:

---

include/range/v3/range_traits.hpp

...and make the trait cv/ref qualifier oblivious.

Teach range_cardinality about arrays

---

include/range/v3/view/concat.hpp
test/view/concat.cpp

[concat] iterator is EqualityComparable only if the base range iterators are.

---

CMakeLists.txt
include/range/v3/action/insert.hpp
include/range/v3/detail/config.hpp
include/range/v3/to_container.hpp
include/range/v3/view/any_view.hpp
include/range/v3/view/transform.hpp
test/algorithm/copy.cpp
test/view/tokenize.cpp

Details:
* CMakeLists.txt: Incorporate the Clang/C2 config block into the Clang config block.
* config.hpp:
* Clang/C2 is emphatically *not* MSVC, even when it's silly enough to claim to be.
* Clang/C2 doesn't define `__GNUC__`, so "gcc and/or clang" must be spelled `defined(__GNUC__) || defined(__clang__)`.
* to_container.hpp: Nitpicky warning fix.
* action/insert.hpp: Nitpicky warning fix.
* view/any_view.hpp: Nitpicky warning fix.
* view/transform.hpp: const correctness fixes for size members of `iter_transform_view` and `iter_transform2_view`.
* test/algorithm/copy.cpp: Nitpicky warning fix.
* test/view/tokenize.cpp: clang is *not* gcc 4.8, despite defining `__GNUC__ == 4 && __GNUC_MINOR__ == 2`

transform: const correctness for size

---

include/range/v3/algorithm/sample.hpp
include/range/v3/algorithm/shuffle.hpp
include/range/v3/algorithm/tagspec.hpp
include/range/v3/detail/config.hpp
include/range/v3/utility/random.hpp
include/range/v3/view/sample.hpp
range-v3.vcxproj
range-v3.vcxproj.filters
test/algorithm/CMakeLists.txt
test/algorithm/sample.cpp
test/algorithm/shuffle.cpp
test/view/CMakeLists.txt
test/view/sample.cpp

* Relocate URNG machinery to utility/random.hpp
* Steal some unpredictable URNG seeding code from the P0347 authors.
* Implement algorithm `sample` from the C++17 WP
* Implement `sample_view`
`sample` has two required implementations: a stable variant for `Forward` source ranges, and an unstable variant for `Input` source ranges with `RandomAccess` result ranges. The stable variant only requires the source range to be `Forward` because it needs to calculate the size. Range-v3 `Input` ranges sometimes know their own size, so range-v3 `sample` uses the stable implementation when the source range is `Forward` or `Sized`.

Implement a few random things.

---

include/range/v3/algorithm/sample.hpp
include/range/v3/utility/random.hpp
test/algorithm/sample.cpp

Don't return `out + n` when we've written less than `n` elements into the result sequence.

sample: handle count > population size in reservoir sampling implementation

---

include/range/v3/algorithm/aux_/equal_range_n.hpp
include/range/v3/algorithm/aux_/lower_bound_n.hpp
include/range/v3/algorithm/aux_/partition_point_n.hpp
include/range/v3/algorithm/aux_/upper_bound_n.hpp
include/range/v3/algorithm/equal_range.hpp
include/range/v3/algorithm/lower_bound.hpp
include/range/v3/algorithm/partition_point.hpp
include/range/v3/algorithm/upper_bound.hpp
test/algorithm/equal_range.cpp

* New algorithm: `aux::partition_point_n`
* `partition_point` exponentially probes for either end-of-range or a value that is past the partition point (doesn't satisfy the predicate), then defers to `partition_point_n` with the narrowed range.
* `lower_bound{_n}` and `upper_bound{_n}` are implemented in terms of `partition_point{_n}`.
* `equal_range` exponentially probes for:
* end-of range or an iterator that is past-the-end of the target range (denotes an element greater than the desired value), at which point it defers to `equal_range_n`.
* an iterator inside the target range (denotes an element equal to the desired value), at which point it delegates to `lower_bound_n(stuff-before-the-iterator)` and `upper_bound(stuff-after)`.
* Fix projection bug in `equal_range_n`; add test …

single-pass implementations of the partition_point family

---

include/range/v3/detail/config.hpp
include/range/v3/utility/random.hpp

I don't have a development environment to test a proper fix, so someone else can fix this. Or complain that it's broken.
Closes #407.

Kill default_random_engine on IPhone.

---

include/range/v3/utility/box.hpp
include/range/v3/utility/random.hpp
include/range/v3/view/const.hpp
include/range/v3/view/move.hpp
include/range/v3/view/single.hpp
include/range/v3/view/transform.hpp
include/range/v3/view_adaptor.hpp
test/algorithm/sample.cpp

* Clang/C2 lies about `__has_builtin(__builtin_readcyclecounter)`
* alg.sample test compares array iterator with pointer.
* `view::const`:
* const correctness (no joke) for `size`
* Don't return references bound to temporary iterators. This is insane with sub-forward iterators, and may be on shaky ground for general proxy iterators. (Does the reference denote an object? Where does that object live? What is the required lifetime of a reference bound to an iterator?)
* `view::move`: Same.
* `noexcept` specifications for remaining `box` constructors.
* Make `view::single::cursor`'s value constructor explicit
* view/transform.hpp need not include zip_with.hpp ("zip" appears only in a comment.)
* `adaptor_cursor`: inherit `compressed_pair` via `detail::adaptor_value_type_` instead of directly …

Miscellaneous fixes:

---

doc/index.md
include/range/v3/view.hpp
include/range/v3/view/drop_exactly.hpp
include/range/v3/view/slice.hpp
range-v3.vcxproj
range-v3.vcxproj.filters
test/view/CMakeLists.txt
test/view/drop_exactly.cpp

i.e., `drop(rng, n)` is an empty range if `rng` has less than `n` elements instead of a precondition violation.
Fixes #413.

Implement drop a la take, instead of take_exactly.

---

include/range/v3/utility/iterator_concepts.hpp

Libc++ reverse_iterator::operator- is non-conforming. 
Closes #420.

[libc++] workaround underconstrained reverse_iterator::operator-

---

.travis.yml
include/meta/meta.hpp
install_libcxx.sh

- re-enable clang-trunk in travis-ci,
- add new version of cmake (required to compile libc++-trunk, the one in travis is too old),
- test clang-trunk in C++1z mode as well, and
- meta: workaround [clang bug 28385](https://llvm.org/bugs/show_bug.cgi?id=28385).

[travis-ci] re-enables clang 3.8

---

include/range/v3/utility/iterator_concepts.hpp
test/utility/iterator.cpp

* Two random-access iterators don't necessarily model `SizedSentinel`, two input iterators may. `SizedSentinel<std::reverse_iterator<S>, std::reverse_iterator<I>>` should require `SizedSentinel<I, S>`.
* Quick regression test.
EDIT: Apply the fix for libstdc++ as well, which implements the resolution of LWG685 incorrectly.

Sharpen the fix for #420.

---

include/range/v3/utility/box.hpp

...and won't need the `could_be_lambda` workaround.

GCC 6.2 will fix PR 71117

---

include/range/v3/view/zip_with.hpp
test/view/zip.cpp

zip_with's underlying iterators do not always model Sentinel

---

include/range/v3/utility/polymorphic_cast.hpp
include/range/v3/view/any_view.hpp

- Add `polymorphic_downcast` to `utility/polymorphic_cast.hpp` with Boost license
- Replace `dynamic_cast` with `polymorphic_downcast` in `any_view` for speed gain in release builds

Replace dynamic_cast with polymorphic_downcast in any_view

---

doc/Doxyfile.in
include/meta/meta.hpp
include/range/v3/utility/compressed_pair.hpp
include/range/v3/utility/functional.hpp

Fixes a couple Doxygen warnings.
Also added special handling for `RANGES_INLINE_VARIABLE`, `CONCEPT_REQUIRES_`, and `CONCEPT_REQUIRES`.
- The `RANGES_INLINE_VARIABLE` fix is needed for Doxygen to correct treat preceding annotations as applying to the function object rather than the namespace.
- The `CONCEPT_REQUIRES` and `CONCEPT_REQUIRES_` change replace them with slightly more readable pseudocode instead of something like `int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(Range< Rng & >()&&Function< Action, Rng &, Rest &&... >()), int >::type = 0`, which is rather ridiculous in documentation.

Various simple Doxygen fixes.

---

doc/CMakeLists.txt
doc/clean-gh-pages.cmake

Right now at least on my system it's seemingly trying to remove a file literally named `*.meow` rather than all files with the extension `meow`.

Make gh-pages.clean actually clean

---

README.md
appveyor.yml
include/range/v3/detail/config.hpp

We (I?) now officially support Clang/C2 in range-v3.

Add AppVeyor CI for Clang/C2; update README

---

appveyor.yml

I apparently never managed to correctly test the AppVeyor build script in the "cmake is cached" case.

[AppVeyor] Fix cmake caching bug

---

include/range/v3/detail/variant.hpp
include/range/v3/iterator_range.hpp
include/range/v3/utility/compressed_pair.hpp
include/range/v3/utility/safe_int.hpp

Adds explicit global namespace specifier in std spezialisations.
Currently this is done very inconsistent which breaks compatibility e.g. with the C++ reflection proposals, which introduces an std::meta namespace.

Consistently specify global namespace

---

.travis.yml
install_libcxx.sh

This patch fixes the Clang and libcxx travis builders. The main changes are:
1. Upgrade to Clang 4.0 since that's what the llvm-nightly repository contains.
2. Rewrite the install_libcxx.sh script so it works better, and supports building with sanitizers.

Fix Clang and libc++ Travis build

---

include/range/v3/algorithm/inplace_merge.hpp
include/range/v3/utility/functional.hpp
include/range/v3/view/filter.hpp
include/range/v3/view/group_by.hpp
test/algorithm/sort.cpp
test/algorithm/stable_sort.cpp
test/utility/functional.cpp
test/view/remove_if.cpp

* call operators forward value category
* call operators SFINAE on return type of the wrapped function
* extension: call operators propagate `noexcept`
* Keep the name `not_` around with a deprecation notice

Rename not_ to not_fn, implement as in the C++17 WP:

---

CMakeLists.txt
cmake/TestHeaders.cmake

Also, the header checks are now implemented as normal targets, which means they are performed whenever a header changes and at build-time, instead of at CMake configure-time.
If the current behavior is preferred, feel free to discard this PR. I simply wrote the `HeaderTests` module for Hana and thought it might be useful elsewhere.

Use a reusable CMake module to perform the header checks

---

include/range/v3/detail/config.hpp

Explicitly qualify use of static_const in RANGES_INLINE_VARIABLE

---

include/range/v3/detail/optional.hpp
include/range/v3/view/adjacent_remove_if.hpp
include/range/v3/view/cycle.hpp
include/range/v3/view/drop.hpp
include/range/v3/view/drop_exactly.hpp
include/range/v3/view/drop_while.hpp
include/range/v3/view/remove_if.hpp
include/range/v3/view/reverse.hpp
include/range/v3/view/slice.hpp

A rule-of-five wrapper for an optional iterator that points into a contained range. Does not copy/move construct/assign the iterator, but *does* invalidate the cached value when assigned, or when used as the source of a move (i.e., invalidates the cache when the range into which it points has presumably been assigned to / moved from.)
Use to simplify the "caching" views:
* adjacent_remove_if
* cycle
* drop
* drop_exactly
* drop_while
* remove_if
* reverse
* slice

Implement non_propagating_cache:

---

include/range/v3/range_access.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/iterator.hpp
test/utility/iterator.cpp

an `OutputCursor` without `next` acts as its own proxy type.

Make "next()" optional for OutputCursors;

---

include/range/v3/detail/config.hpp
include/range/v3/view/sample.hpp

* `RANGES_ASSERT(pred)`
* Implement by hand on GCC4, instead of using `assert` from the standard library, so that `RANGES_ASSERT `is usable in `constexpr` functions. (This is not the case for `assert` in libstdc++ for GCC < 5.)
* Add `RANGES_ASSUME(pred)`
* Has undefined behavior if `pred` is not `true`. (Makes an effort to inform the optimizer that `pred` must hold.)
* Unlike `RANGES_ASSERT(pred)`, which does not evaluate `pred` in release builds, `pred` is *always* potentially evaluated. It must be inexpensive to evaluate.
* Add `RANGES_EXPECT(pred)`
* When debugging (`!defined(NDEBUG)`), equivalent to `RANGES_ASSERT(pred)`.
* When NOT debugging, equivalent to `RANGES_ASSUME(pred)`.
Replace `void()` with `void(0)` throughout the contract system to workaround …

Rework contract enforcement system:

---

include/range/v3/utility/functional.hpp
test/utility/functional.cpp

Function pointers are already perfectly good function objects. Fixes Microsoft/Range-V3-VS2015#11.
While I'm here, throw some constexpr & noexcept at as_function_fn and defend logical_negate_'s perfect forwarding constructor against recursive instantiation.

[as_function] Don't wrap function pointers.

---

include/range/v3/view/zip_with.hpp

Silences truncation warning in test/view/keys_value.cpp to fix the AppVeyor Clang/C2 build.

Properly constrain detail::advance_::operator()

---

include/range/v3/range_fwd.hpp
include/range/v3/utility/associated_types.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/iterator_concepts.hpp

...so that `foo<const T>` works correctly when `T` is a class type with member `foo_type`.
I tried to give `difference_type` the same overload-set design as `value_type` and `iterator_category`, and fell face-first into a steaming pile of recursive instantiation errors: it's critical that the code does not attempt to instantiate `T - T` when `T` has a member `difference_type`.

Disambiguate iterator_category and difference_type

---

include/range/v3/algorithm/swap_ranges.hpp
test/algorithm/swap_ranges.cpp

* `swap_ranges(a, a+n, b)` should work for array `a` & `b`
* `swap_ranges(a, b)` should work for rvalue `a` and iterator `b`

Fix swap_ranges:

---

include/range/v3/action/erase.hpp
include/range/v3/action/push_back.hpp
include/range/v3/action/push_front.hpp
include/range/v3/range_concepts.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/iterator_concepts.hpp

Also turn some instances of `<expression>` into `((void)(<expression>), 42)` in concept definitions when `<expression>` has user-defined type and could hijack the comma operator.

Eradicate concepts::val and concepts::val_t

---

include/range/v3/view/any_view.hpp

Consider:
```c++
using T = indexed_element<any_view<int>, 0>;
CONCEPT_ASSERT(InputRange<T>());
```
`T` is a `Range` if you can call `begin` on it. You can call `begin` on a `T` if it is convertible to `any_view<int>`. `T` is convertible to `any_view<int>` if it is a `Range`...
Related to ericniebler/range-v3#547.

Avoid constraint recursion converting to any_view

---

test/container_conversion.cpp

Since range-v3 dropped support for g++-4.9.2, issue #556 is probably not an issue anymore. If tests pass, this closes #556.

Add test for issue #556

---

include/range/v3/view/cycle.hpp

Fix constructor in view::cycle, which uses a moved-from variable

Fix assertion in view::cycle

---

.travis.yml
example/CMakeLists.txt
example/calendar.cpp

- The `.travis.yml` file now: 
- has boost_url/boost_version as global flags
- the jobs have a boost=on/off environment flag
- the script fetches and builds boost from source for clang when boost=on
- builds the calendar example when boost=on for clang trunk -std=c++1z without sanitizers 
- The `chunk_view` in the calendar example is scoped inside a namespace to prevent it from clashing against `ranges::chunk_view` which is in scope if modules are used because the example uses `using namespace ranges;`. 
TODO:
- get a gcc build bot building the calendar example as well (issue #596) . 
Closes #223 (now the calendar example builds on clang-trunk on linux automatically).

[travis-ci] build the calendar example with clang-trunk on linux

---

include/range/v3/size.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/view_interface.hpp

* `iter_size` can work fine with *references* to single-pass iterators
* `view_interface` should not trash single-pass ranges by calling `iter_size(begin(), end())`
* `size` should not trash single-pass ranges by calling `iter_size(begin(), end())`

Fix some size + single-pass bugs:

---

include/range/v3/to_container.hpp
include/range/v3/utility/common_tuple.hpp
include/range/v3/utility/functional.hpp
include/range/v3/utility/tuple_algorithm.hpp
include/range/v3/view.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/concat.hpp
test/view/CMakeLists.txt
test/view/cartesian_product.cpp

* Expose `common_tuple::base`
* Move `detail:deref_fun` into functional.hpp and rename to `dereference` so `cartesian_product can reuse it
* Drive-by:
* Polish constraints in `to_container`
* sort view.hpp
* Pass function objects by reference internally in the tuple algorithms

Implement view::cartesian_product

---

include/range/v3/view.hpp
include/range/v3/view/indices.hpp
include/range/v3/view/iota.hpp
test/view/iota.cpp

- Deprecate `closed_ints`. 
- add `view::indices/inclusive_indices`
- [bugfix]: fix unsigned integer wrap around which caused weird behavior like a range of size of `0` that can be iterated for`ints`/`closed_ints`/`indices`/`inclusive_indices` :
- assert on signed integer overflow by requiring `to - from < std::numeric_limits<T>::max()` for`ints`/`closed_ints`/`indices`/`inclusive_indices`
Closes #470 (at least the "bug" part of it. @CaseyCarter: it might be worth it to move your ideas for infinite ranges to its own issue to pursue them further).
Closes #277 .
Supersedes #592 .

add view::indices, deprecate closed_ints

---

include/range/v3/utility/concepts.hpp

Also, `Destructible` doesn't check for sane address-of operator (refs ericniebler/stl2#382)

Get range-v3 to compile with gcc-5.2 (fixes #614)

---

include/range/v3/utility/functional.hpp

Avoids some nasty interaction between defaulted and inherited default constructors that manifests with g++-4.9 in utility.variant and view.transform.

Default the default constructor of overloaded

---

include/meta/meta.hpp
include/range/v3/action/action.hpp
include/range/v3/action/join.hpp
include/range/v3/action/reverse.hpp
include/range/v3/action/sort.hpp
include/range/v3/action/stable_sort.hpp
include/range/v3/range_fwd.hpp
include/range/v3/utility/functional.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/view/for_each.hpp
include/range/v3/view/view.hpp
test/action/CMakeLists.txt
test/action/join.cpp
test/action/stable_sort.cpp

Also:
- fix up many action concept tests
- add tests for `action::stable_sort` and `action::view`
fixes #632

Defer Invokable test in ranges::action

---

include/meta/meta.hpp

* 	Restrict meta:: workaround for CWG#1558 to older gcc versions
* 	simplify implementation of meta::defer and meta::defer_i

Meta improvements

---

CMakeLists.txt

For some reason, MSVC 2017 (clang/C2) failed to find header files during debugging (displaying the "Source not found..." page). Adding the headers to the solution fixes the problem.

Fix MSVC debugging issues

---

include/range/v3/numeric/adjacent_difference.hpp
include/range/v3/numeric/inner_product.hpp
include/range/v3/numeric/partial_sum.hpp

`unreachable`'s `constexpr` checks should have no effect on the code generation (and looking at optimized assembly in clang/cl - it indeed doesn't).

Reducing duplication with unreachable{} (numeric)

---

include/range/v3/detail/config.hpp

Fixes #654.
MinGW's `assert` is not `[[noreturn]]`.

Use ranges::detail::assert on MinGW

---

include/range/v3/utility/random.hpp
test/utility/functional.cpp

* Many MinGW distros don't implement `<thread>`, so don't use `std::this_thread::get_id()` as a source of entropy in `local_entropy`
* MinGW apparently does not support the `vectorcall` calling convention. range-v3 does not care: we only use Windows' calling conventions to validate that `Invocable` handles them properly.
Fixes #654 even fixier.

More MinGW compile fixes:

---

CMakeLists.txt
test/getlines.cpp
test/view/replace_if.cpp

Partially addresses #659
* Disable `-Wnoexcept-type` globally
* Perma-workaround `-Wstrict-aliasing` false positive in getlines.cpp ([GCC PR 80633](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80633))
* Disable `-Wmaybe-uninitialized` in view/replace_if.cpp (I *think* this is a false positive, but it needs proper investigation.)

Build on GCC 7

---

include/meta/meta.hpp
include/range/v3/action/action.hpp
include/range/v3/empty.hpp
include/range/v3/front.hpp
include/range/v3/getlines.hpp
include/range/v3/istream_range.hpp
include/range/v3/iterator_range.hpp
include/range/v3/range_concepts.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/chunk.hpp
include/range/v3/view/concat.hpp
include/range/v3/view/const.hpp
include/range/v3/view/cycle.hpp
include/range/v3/view/indirect.hpp
include/range/v3/view/intersperse.hpp
include/range/v3/view/partial_sum.hpp
include/range/v3/view/reverse.hpp
include/range/v3/view/sample.hpp
include/range/v3/view/set_algorithm.hpp
include/range/v3/view/take.hpp
include/range/v3/view/take_exactly.hpp
include/range/v3/view/tokenize.hpp
include/range/v3/view/view.hpp
include/range/v3/view_interface.hpp
test/istream_range.cpp
test/view/tokenize.cpp

Things I found while investigating move-only input views.
* Implement `meta::add_const_if` directly to avoid defer overhead. Add friendlier `meta::const_if` front-end for `add_const_if`. (Not a bugfix)
* Implement `empty` per the Ranges TS spec.
* `front` now requires a forward range. It's not technically *wrong* on input ranges, but all the uses in the library are bugs.
* `getline_` and `istream_range` can use the default `iter_move`; don't implement `move()` in their cursors. (Not a bugfix)
* `istream_range<T>` doesn't require `T` to be `MoveConstructible`, so `istream()` needs to construct its return object in-place.
* Implement `empty` for `iterator_range` since the default implementation in `view_interface` no longer works for input ranges (see below)
* remove unnecessary …

Batch of bugfixes

---

CMakeLists.txt
cmake/coro_test_code.cpp
include/range/v3/detail/config.hpp
include/range/v3/experimental/utility/generator.hpp
test/CMakeLists.txt
test/generator.cpp

* Cmake support for detecting `-fcoroutines-ts` compiler flag and library support in `<experimental/coroutine>`
* Config system support for `RANGES_CXX_COROUTINES`
* Implement coroutine Range generator `ranges::experimental::generator`, and SizedRange generator `ranges::experimental::sized_generator`

Implement coroutine generator support

---

.travis.yml

Yes, this means we cannot have Travis both (a) build libc++ and (b) validate that our CMakeLists don't use features newer than version 3.0 which we require.
\*shrug\*

Travis: cmake version churn: libc++ needs a newer cmake

---

include/range/v3/view/chunk.hpp
include/range/v3/view/iota.hpp
test/view/chunk.cpp

Reported in #567.
Drive-by: In `iota_difference_`, `sizeof(difference_t) * CHAR_BIT < 8` is impossible.

Fix bug in the input-range specialization of chunk_view

---

CMakeLists.txt

When range-v3 was in a subdirectory of a project foo and
add_subdirectory(range-v3) was called from the CMakeLists.txt
of project foo, an error message was raised when running cmake:
""
CMake Error at range-v3/cmake/TestHeaders.cmake:93 (message):
The `HEADERS` argument must be provided.
Call Stack (most recent call first):
range-v3/CMakeLists.txt:103 (generate_standalone_header_tests)
""
RANGE_V3_PUBLIC_HEADERS was empty, because the variable
CMAKE_SOURCE_DIR was used.
Using CMAKE_CURRENT_SOURCE_DIR instead fixed the issue.

Fix #671 - CMakeLists.txt when including it from a parent directory

---

doc/index.md

Markdown was missing http:// prefix, so acted like a local page ref

Fix broken link to N4128 document

---

include/range/v3/action/insert.hpp
include/range/v3/action/push_back.hpp
include/range/v3/action/push_front.hpp
test/action/join.cpp

when a range is its own sentinel (e.g. std::string), resolve overloads in favor of Range

---

include/range/v3/action/concepts.hpp
include/range/v3/action/insert.hpp
include/range/v3/to_container.hpp
test/action/insert.cpp

WG21 really should fix this in `std::vector::reserve`: when the argument to `reserve` is greater than the current capacity and less than the next exponential growth target, round it up.
There are also a bunch of unrelated style changes in action/insert.hpp, which I really should have put into a distinct commit to make it easier to review the behavioral changes. Those actual behavior changes are in the `insert_impl` overloads defined on 119 and 142, which call a new `insert_reserve_helper` defined on 86.
EDIT: I've also added some overflow paranoia to insert and `to_container`, and fixed `to_container` to properly use `ranges::size` instead of `foo.size()`.

insert action should not break vector's exponential growth

---

include/range/v3/action/concepts.hpp
include/range/v3/begin_end.hpp
include/range/v3/detail/variant.hpp
include/range/v3/empty.hpp
include/range/v3/range_fwd.hpp
include/range/v3/size.hpp
include/range/v3/utility/functional.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/utility/semiregular.hpp
test/utility/functional.cpp

Also, change the spelling of a wrapper of an rvalue from `reference_wrapper<T, true>` to `reference_wrapper<T &&>`.
Future: Further consider combining this with `box<>`.

Rework ranges::reference_wrapper in light of LWG#2993

---

.travis.yml
include/range/v3/at.hpp

Re-enable constexpr 14 support on GCC 5 in `.travis.yml`
(Also strip the UTF-8 BoM from .travis.yml - no idea how it got one.)

Workaround gcc5 constexpr 14 bug in at_fn

---

include/range/v3/utility/invoke.hpp

Makes clang-trunk happy again.

remove redundant parens

---

include/range/v3/algorithm/equal.hpp
include/range/v3/utility/functional.hpp
test/algorithm/equal.cpp

Make the `ranges::equal` algorithm constexpr.

[constexpr] alg.equal

---

include/range/v3/utility/box.hpp
include/range/v3/view/stride.hpp
include/range/v3/view_adaptor.hpp
test/view/stride.cpp

stride views must track the distance in the base range between the last dereferenceable iterator and the end iterator ("offset"). The offset is used when decrementing bidirectional end iterators. Since there's one unique offset value per underlying range, we can store a single offset value in the stride_view rather than in each of its iterators.
Using a mutable std::atomic to store the offset and provide const-iterable stride_views was a design mistake: all users pay the cost of the atomic despite that few users will actually access the same stride_view simultaneously from multiple threads. Let's instead store the offset in a plain vanilla member variable, and make the view not const iterable when it must update the offset during iteration.

stride_view refactor:

---

include/range/v3/view/adjacent_remove_if.hpp
include/range/v3/view/remove_if.hpp
test/view/adjacent_remove_if.cpp

* Store the predicate in a `box` for EBO
* Only adapt the sentinel if it's an iterator
* Don't cache an incorrect begin iterator if an exception is thrown in satisfy_forward
* constexpr and noexcept
* Use `base()` instead of `mutable_base()` to access the underlying range
* `adjacent_remove_if`:
* model `BidirectionalRange` when the base range does

(adjacent_)?remove_if cleanup:

---

include/range/v3/view/reverse.hpp

* Don't use `mutable_base` (it was hiding a const bug in the `BoundedRange` implementation of `get_end` when `!Range<Rng const>()`)
* constexpr / conditional noexcept all the things

reverse_view cleanup:

---

include/range/v3/range_access.hpp
include/range/v3/view_adaptor.hpp
include/range/v3/view_facade.hpp
include/range/v3/view_interface.hpp

Fixes #726.
`view_adaptor`:
* decay the types of `(begin|end)_adaptor_t` and `adapted_(iterator|sentinel)_t`
* Deduce return type/noexcept for `adaptor_base::(begin|end)`
* remove `base_range_t`
* remove `mutable` specifier from base range, and remove `mutable_base()`
* constexpr / noexcept
`view_facade`:
* decay the types of `begin_cursor_t` and `end_cursor_t`
`view_interface`:
* Cleanup constraints on `empty`
* DRY the range printing code
`range_access`:
* conditional noexcept for `(begin|end)_(adaptor|cursor)`
* Remove `base_range`

view_adaptor update

---

include/range/v3/detail/satisfy_boost_range.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/move.hpp
test/view/counted.cpp

When the base iterator's post-increment operator has `void` return type, we can't bind a reference thereto.

counted_iterator: fix post-increment bug

---

test/span.cpp
test/view/any_view.cpp

...disable the workarounds for clang >= 6

LLVM 33314 is purportedly fixed on trunk

---

include/range/v3/view_adaptor.hpp

...with `Range<foo const>()`. Compilers - clang 5, at least - cache the value of *successful* template substitution, not the value of *failed* template substitution.
Fixes #758.

view_adaptor: guard const overloads of (begin|end)_cursor

---

include/meta/meta.hpp
install_libcxx.sh

The changes to `meta.hpp` mirror those in ericniebler/meta#54.

Improved 28385 workaround

---

doc/std/D4128.md

is_word_boundary example using C++ iterators was incorrectly returning
void, while it should return bool.

[doc] Change return type of is_word_boundary to bool

---

CMakeLists.txt
cmake/TestHeaders.cmake
example/CMakeLists.txt
perf/CMakeLists.txt
test/CMakeLists.txt
test/action/CMakeLists.txt
test/algorithm/CMakeLists.txt
test/experimental/utility/CMakeLists.txt
test/experimental/view/CMakeLists.txt
test/numeric/CMakeLists.txt
test/utility/CMakeLists.txt
test/view/CMakeLists.txt

I have integrated range-v3 into my library, however, the current CMakeLists.txt makes it almost impossible.
With my changes, one can use `add_subdirectory(range-v3)` and `target_link_libraries(foo range-v3)` to "link" the library to the target "foo".
See [my example](https://github.com/verri/jules/blob/8a42b703d4cfe795124291f502cabe4259111310/CMakeLists.txt#L73).
Other convenient changes:
- I've added `RANGE_V3_NO_{TESTING,EXAMPLE,PERF}`, so one can opt for a "light" integration; and
- I've added `range-v3-config.cmake` in the installation.

cmake interfaces and better installation.

---

include/range/v3/view_interface.hpp
test/view/remove_if.cpp

Assume that ranges with infinite cardinality are never empty.
Fixes #793.
Drive-by: sprinkle some constexpr on view_interface

Implement non-const view_interface::empty and ::size

---

include/range/v3/span.hpp
test/span.cpp

span::subspan<N, -1>() is equivalent to subspan<N>()

---

include/range/v3/view/split.hpp
test/view/split.cpp

...to accommodate usage in the `cursor` constructor.
Bug reported at https://stackoverflow.com/questions/49015671

[split_view] split functions must also accept (iterator, iterator)

---

conanfile.py

I noticed that you (or your CI) are not building a binary package for Conan, just uploading the recipe, that, of course in your case, contains all the needed headers.
In this case, when a consumer of your library tries to install it, it will fail because it doesn't find the binary package available, and the consumer have to specify `--build range-v3` or `--build missing`. To improve the UX, for header only libraries there are two possible approaches:
a) The author generates the unique binary package (no settings involved, so there could be only 1 package) and uploads it together with the recipe.
b) The author specifies "build_policy=missing", so the package will be created on the fly.
This PR provides b).
Luis

Build missing: Automatic package creation

---

include/range/v3/view/stride.hpp
test/view/stride.cpp

@CaseyCarter I feel that `stride` needs a thorough rethink, but this puts a bandaid on the problem for now.
A better design, IMO, would be for a `stride` view of a Bidirectional, Common ("Bounded"), non-Sized range would not attempt to satisfy CommonRange since the end iterator could not be correctly decremented in O(1); the offset is not yet known.

fix bug with decrementing the end of a non-const-iterable, bounded, bidirectional stride view

---

include/range/v3/view/drop.hpp
test/view/drop.cpp

view::drop is not drop_exactly: don't overrun random access ranges

---

.travis.yml
CMakeLists.txt
cmake/ranges_options.cmake

These options are visible from the cmake-gui and cmake-curses-gui;
their presence is more discoverable than the local variables used
previously.
In addition, the default values for these options is contingent
upon whether range-v3 is the highest level project. When range-v3
is composed in another project (as a git submodule, for instance)
tests are not built and no option appears in the GUI.

Added explicit options to enable or disable testing

---

include/range/v3/algorithm/stable_sort.hpp
include/range/v3/detail/config.hpp
include/range/v3/range_fwd.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/common_iterator.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/move.hpp
include/range/v3/utility/tagged_pair.hpp

Move class template declarations from nested detail namespaces into `ranges:v3`, and - on clang only - implement friends with the same names as CPOs in those same detail namespaces. This affects:
* `tagged`
* `basic_iterator`
* `common_iterator`
* `counted_iterator`
NOTE TO REVIEWERS: This changes indentation for some big chunks of code, you may want to ignore whitespace changes to focus on the actual differences.

Don't workaround clang 37556 on non-clang

---

CMakeLists.txt
README.md
appveyor.yml
cmake/ranges_env.cmake
cmake/ranges_flags.cmake
example/comprehensions.cpp
include/meta/meta.hpp
include/range/v3/detail/adl_get.hpp
include/range/v3/detail/config.hpp
include/range/v3/utility/common_tuple.hpp
include/range/v3/utility/move.hpp
include/range/v3/utility/safe_int.hpp
include/range/v3/utility/tagged_pair.hpp
include/range/v3/utility/tuple_algorithm.hpp
test/algorithm/merge.cpp
test/algorithm/partition_copy.cpp
test/algorithm/set_symmetric_difference.hpp
test/algorithm/set_union.hpp
test/algorithm/transform.cpp
test/span.cpp
test/view/zip.cpp

Individual commit logs:
* LLVM 28385 is fixed in clang 6
* Always implement `RANGES_ASSERT` on MSFTL
`assert` failures don't necessarily terminate the program on Windows. In addition to being silly, this is problematic for range-v3 since we sometimes write:
```c++
[[noreturn]] void foo() {
RANGES_EXPECT(false);
}
```
and clang will complain about this `[[noreturn]]` function returning.
* Remove bogus `span` test
`std::array`'s iterators aren't necessarily pointers.
* Remove specialization of `std::is_integral` in safe_int
No, no, no! BAD!
(Also, don't check `is_literal` since it's deprecated in C++17.)
* Support clang-cl, drop ClangC2 like a hot potato
* Travis changes:
* Define `_SILENCE_CXX17_TEMPORARY_BUFFER_DEPRECATION_WARNING` when building on MSFTL to silence deprecation warnings …

Clang/C2 is dead - long live ClangCL!

---

README.md
include/meta/meta.hpp
include/meta/meta_fwd.hpp
include/range/v3/algorithm/equal.hpp
include/range/v3/begin_end.hpp
include/range/v3/data.hpp
include/range/v3/detail/config.hpp
include/range/v3/detail/variant.hpp
include/range/v3/experimental/view/shared.hpp
include/range/v3/istream_range.hpp
include/range/v3/range_access.hpp
include/range/v3/range_fwd.hpp
include/range/v3/range_traits.hpp
include/range/v3/size.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/iterator_concepts.hpp
include/range/v3/utility/move.hpp
include/range/v3/utility/swap.hpp
include/range/v3/view/all.hpp
include/range/v3/view_facade.hpp
test/algorithm/copy.cpp
test/container_conversion.cpp
test/experimental/utility/generator.cpp
test/test_utils.hpp
test/utility/basic_iterator.cpp
test/utility/meta.cpp

* Eradicate the inline namespace `function_objects`. `RANGES_INLINE_VARIABLE` puts variables directly in the containing namespace when inline variables are available, and in an inline unnamed namespace otherwise.
* *Explicitly* place CPOs that are truly customization points in an inline namespace `CPOs` inside `ranges::v3` (which keeps them from colliding with hidden friend functions of the same name)
(Note that `advance` is a "true" CPO because `counted_iterator` defines a hidden friend overload in namespace `ranges::v3`.)
Bundle of dozens of drive-by changes:
* Implement `meta::at` with `__type_pack_element` when available
* Use wg21.link for LWG issues so we don't need to care about active vs. closed vs. defect [NFC]
* Wrap `view/all.hpp` at 100 [NFC]
* `experimental/view/shared.hpp`: …

Cleanup CPO declarations:

---

include/meta/meta.hpp

Fix #839 macro to the clang version for MacOs

---

include/range/v3/view/any_view.hpp
test/view/any_view.cpp

The sized category information wasn't getting propagated to the implementation.
Apologies if I'm mistaken!

Fixes #869 any_view<Foo, category::sized | category::input>

---

include/range/v3/algorithm/inplace_merge.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/variant.hpp
test/action/stable_sort.cpp
test/algorithm/stable_sort.cpp

We would have found this bug had we been using `ranges::reverse_iterator` in the implementation of `inplace_merge` as opposed to `std::reverse_iterator`. This PR makes that change in addition to a couple of other changes to use `ranges::` facilities instead of `std::` ones.

fix 3-year-old bug in reverse_iterator

---

test/test_utils.hpp

I can only assume that the non-`const` copy constructor was a typo, and a move constructor was intended. I see no reason to forbid assignment of this type, so let's yank both copy constructors.

function_ref: remove unnecessary defaulted copy constructors

---

.vscode/c_cpp_properties.json
include/meta/meta.hpp
include/range/v3/detail/config.hpp
include/range/v3/span.hpp
include/range/v3/utility/common_type.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/utility/iterator_concepts.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/sliding.hpp
include/range/v3/view/zip_with.hpp

* Fix incorrect description for `meta::on`
* Don't violate [temp.deduct.guide]/3 in `span.hpp`
* `iterator_concepts.hpp`: range-v3 uses `typename` for template type parameters, not `class`
* Silence potential warning when `cartesian_product_view::advance_` implicitly converts `difference_type` to `ptrdiff_t`
* `sliding.hpp` fix bad indent
* `zip_with_fn::Concept`: remove redundant `meta::and_` nested in `meta::and_`
* `common_type.hpp`: remove `#if 0` block, and strip extraneous `&&` from the first argument to `is_convertible`.
* Don't put MSVC include path in `c_cpp_propertes`: it's too volatile

Misc cleanup:

---

include/range/v3/view/stride.hpp
test/view/stride.cpp

When "advancing" the end iterator by a negative amount, and the cached "offset" hasn't yet been computed yet, _compute it first_ before using it.

fix bug in stride_view's iterator advance; fixes #901

---

include/range/v3/detail/variant.hpp
include/range/v3/view/generate.hpp
include/range/v3/view/generate_n.hpp
test/view/generate.cpp
test/view/generate_n.cpp

fixes #905
NOTE WELL: This changes generators so that they return xvalue references to the cached value. This is a silent breaking change for some valid code. It is, however, arguably closest to the programmer's intent as I imagine it.
@CaseyCarter, please offer your perspectives here.

make the generate and generate_n views work with move-only types

---

include/range/v3/detail/variant.hpp
include/range/v3/view/generate.hpp
include/range/v3/view/generate_n.hpp
test/view/generate.cpp
test/view/generate_n.cpp

fixes #807 
Includes the controversial fix for #905

the cached value in generate_view and generate_n_view doesn't propagate on copy/move

---

include/range/v3/detail/config.hpp
include/range/v3/range_fwd.hpp

Apple clang's deduction guides are kind of broken in that they occasionally complain about missing definitions(!) of the deduction guides.
Also, when a compiler implements `noexcept` as part of a function's type and the standard library's `std::is_function` implementation isn't hip to that, hijinks ensue. Don't use `std::is_function`.

Portability fixes

---

include/range/v3/view/cartesian_product.hpp
test/view/cartesian_product.cpp

* Use `std::intmax_t` for size and difference types
* Implement `static size` when all `View` types have fixed cardinatlity
* Rethink `advance` (Fixes #919)

cartesian_product_view:

---

include/range/v3/range_fwd.hpp
include/range/v3/view/all.hpp
include/range/v3/view/bounded.hpp
include/range/v3/view/cycle.hpp
include/range/v3/view/reverse.hpp
test/view/reverse.cpp

* Prefer `std::intmax_t` to `std::ptrdiff_t` for "really large signed integer", which matters for 32-bit platforms.
* Don't bother to inefficiently adapt infinite ranges.

cycled_view updates

---

CMakeLists.txt
cmake/aligned_new_probe.cpp
cmake/ranges_flags.cmake
test/CMakeLists.txt

* Refer to `<thread>` and coroutine features checks as "probes"
* Add probe for C++17 aligned new support (since there's no feature detection macro for the library support)
* put the probes in `ranges_flags.cmake` instead of the top-level `CMakeLists.txt`

Bit of cmake cleanup:

---

include/range/v3/detail/config.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/zip.hpp
include/range/v3/view/zip_with.hpp
test/view/cartesian_product.cpp
test/view/zip.cpp

`ranges::view::zip()` is a contiguous range of no elements of type `std::tuple<>`.

[zip] Correctly zip no ranges

---

include/range/v3/view/generate.hpp

Which generates better code when the optimizer can't tell that the generator function doesn't modify the cache.

generate_view: emplace instead of assign the stored value

---

CMakeLists.txt

This change adds an additional way to consume Range-v3 with CMake, other than installing it to use with `find_package` or somehow making it available (say, git submodule or `FetchContent`) to use it with `add_subdirectory`. It permits pointing to an existing build tree of Range-v3 by setting `range-v3_DIR` variable to that directory, so that you can then use it with `find_package` as usual.
My intention is to allow my own libraries depending on Range-v3 to be used by defining their `_DIR` variable, as mentioned above, without needing Range-v3 to be installed.

Allow importing from existing CMake build tree

---

include/range/v3/range_fwd.hpp
include/range/v3/view/filter.hpp
include/range/v3/view/remove_if.hpp
test/view/remove_if.cpp

I missed the same feature as described in #892.
My changes to the view::filter and view::remove_if are mostly based on the projection code used in action::remove_if.
If this patch is accepted, I will have a look on view::take_while.

Projection support on view::filter and view::remove_if

---

include/concepts/concepts.hpp
include/range/v3/action.hpp
include/range/v3/action/split_with.hpp
include/range/v3/range_access.hpp
include/range/v3/range_concepts.hpp
include/range/v3/range_fwd.hpp
include/range/v3/utility/common_iterator.hpp
include/range/v3/utility/counted_iterator.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/utility/iterator.hpp
include/range/v3/utility/iterator_concepts.hpp
include/range/v3/utility/iterator_traits.hpp
include/range/v3/view.hpp
include/range/v3/view/all.hpp
include/range/v3/view/drop.hpp
include/range/v3/view/join.hpp
include/range/v3/view/split.hpp
include/range/v3/view/split_with.hpp
include/range/v3/view/take.hpp
include/range/v3/view/transform.hpp
include/range/v3/view/zip_with.hpp
include/range/v3/view_adaptor.hpp
test/action/split.cpp
test/view/join.cpp
test/view/split.cpp

* break `view::split` and `action::split` into `split` and `split_with`
* `view::split` conforms to C++20

view::split and action::split refactorization

---

include/range/v3/view/partial_sum.hpp
test/view/partial_sum.cpp

* Replace bogus `ConvertibleTo<invoke_result_t, range_value_t>` constraint
* Don't use `view_adaptor`
* `RANGES_UNIQUE_ADDRESS` all the things
* Never model `CommonRange`. There's little to be gained by making a forward range common, and doing so harms perf on the benchmark (https://stackoverflow.com/questions/44413446/why-is-range-v3-slower-than-the-stl-in-this-example).
This brings the slowdown relative to STL in the benchmark down to 1.6x, which seems to be the best we can do: my "put everything in the iterator" investigations were actually slower. I'll let you decide if this is good enough to close #668.

partial_sum_view refactor:

---

include/range/v3/utility/semiregular.hpp

I got some broken-ness through changing to v1.0-beta which this little patch resolves. I assume the conditional noexcept was just forgotten?

make semiregular copy constructor be conditionally noexcept

---

include/concepts/concepts.hpp
include/range/v3/view/transform.hpp

* [NFC] Remove unused `_concepts_int_` type alias
* Workaround MSVC's aversion to `explicit operator bool` in constant expressions.
This raises the bar from 6% tests passing to 32% (With VS2019 + not-yet-released bugfix)

More MSVC 1.0 work

---

include/range/v3/view/split_when.hpp
test/view/split.cpp

Drive-by: simplify `zero_` handling in `cursor::next`
Fixes #1041.

split_when_view: fix bogus initial-zero-match check in cursor constructor

---

include/range/v3/view/join.hpp

This is a warning introduced in newer versions of clang.

Fix -Wextra-semi-stmt: remove unnecessary semicolon.

---

CMakeLists.txt
cmake/ranges_options.cmake

When range-v3 is being used as a standalone project (i.e., not a
subproject) then behavior should stay the same, in that the building
of tests/examples/etc. is enabled by default, but still settable
by the user using the same variables.
However, if range-v3 is a subproject of a parent then we will attempt
to respect the parent's settings regarding testing.  In that situation:
* Testing/header checks are disabled by default.
* Examples/docs/perf targets are disabled by default.
* Enable testing/header checks if the parent has already enabled
testing.
Effectively this causes the range-v3 subproject to mirror the testing
status of its parent, but while still allowing customization using
the usual variables.
This change was tested with CMake 3.13 in the following configurations:
1) range-v3 …

Improve logic controlling the enabling of testing.

---

CMakeLists.txt
cmake/ranges_options.cmake

Removed some comments and changed testing defaults in ranges_options.cmake from `BUILD_TESTING` to `OFF`. This ensures that when range-v3 is a subproject and consumed with `add_subdirectory` that the tests will not build or register with ctest.

testing is disabled when subproject

---

include/range/v3/view/linear_distribute.hpp
test/view/linear_distribute.cpp

The `from_` values are only equal if the `n_` values are.
Fixes #1088.

linear_distribute_view: fix equal

---

include/range/v3/view/take.hpp

This fixes #1092 for me. The workaround would always work, but I have just activated it for ConceptsTS, because I don't know what your general policy for platform specific workarounds is.

[FIX-#1092] view::take has problems with GCC+ConceptsTS

---

README.md
cmake/ranges_flags.cmake
include/meta/meta_fwd.hpp
include/range/v3/detail/config.hpp
include/range/v3/range/access.hpp
include/std/iterator
test/iterator/iterator.cpp
test/range/conversion.cpp

* iter.iterator:
* remove extraneous typename disambiguators applied to non-dependent types
* don't redundantly test that contiguous iterator is random access
* Use `__has_include` to detect `<string_view>` in `range/access.hpp`
* Workaround VSO#792338 "Failure to match specialization enabled via call to constexpr function"
* Workaround VSO#793042 in `<iterator>`
* Workaround VSO#779708 again
* VS2019: Disable unneeded MSVC workarounds
* Update README
* Disable C5105 "macro expansion producing 'defined' has undefined behavior"

MSVC 1.0 updates (again)

---

include/range/v3/detail/config.hpp
include/range/v3/experimental/utility/generator.hpp
test/experimental/utility/generator.cpp

* Avoid VSO#835948 "Silent bad codegen for sized_generator" in test.generator
* Warn that clang-cl doesn't speak coroutine
* Warn that MSVC miscompiles `sized_generator`

MSABI coroutine issues:

---

include/range/v3/view_adaptor.hpp
test/view_adaptor.cpp

This PR adds ability to use mixin in adaptor.
Interface:
```cpp
class adaptor : public ::ranges::adaptor_base
{
template<class base_mixin>
struct mixin : base_mixin
{
mixin() = default;
using base_mixin::base_mixin;
decltype(auto) base_value() const
{
return *base.value();
}
int get_i() const
{
return this->adaptor().i;
}
};
int i = 100;
};
```
`adaptor()` is only visible from inside mixin.
`base()` - visible everywhere.
Work for both - cursor and sentinel adaptor versions.

mixin for adaptor (view_adaptor) v2

---

include/range/v3/view/generate_n.hpp

This small change makes generate_n as fast as plain for-loop. 8x speed up with generated monotonically increasing int sequence (in compare to current version).
`emplace` has less branches then =. Because operator= also supports move assign value. This will never happens in `generate_n`.

view::generate_n cache update optimisation

---

CMakeLists.txt
cmake/TestHeaders.cmake
cmake/ranges_options.cmake

This prevents the massive amount of generated targets from appearing in graphical contexts that overshadow the local project's targets.

Update TestHeaders CMake module

---

include/range/v3/utility/basic_iterator.hpp
include/range/v3/view_adaptor.hpp
test/view_adaptor.cpp

This https://github.com/ericniebler/range-v3/pull/1099
Making `adpator mixin` `basic_iterator mixin` conformant. 
Accessing to iterator guts with `get()` everywhere.

Adaptor mixin v3 bis

---

include/range/v3/detail/config.hpp

Currently range-v3/master does not build when targeting iOS, due to iOS lacking support for aligned new.
This PR disables aligned new when `_LIBCPP_HAS_NO_ALIGNED_ALLOCATION` is defined which allows range-v3 to build for iOS targets.

fix libcpp aligned new detection for iOS

---

include/concepts/concepts.hpp

The standard only allows the following syntax 
```c++
template <typename t>
concept AnyType = true; // gcc >= 9 and clang
```
but ranges currently uses 
```c++
template <typename t>
concept bool AnyType = true; // only way to define concepts gcc<9
```
-----
clang will not allow the additional `bool`.
This PR will add the concept definition without the `bool` and uses it in the same manner as it is already handled in the meta library, see
https://github.com/ericniebler/range-v3/blob/75d96cfeabf6366012090594382bda635b6cfb38/include/meta/meta_fwd.hpp#L138-L153
Open Questions:
* Would it also be okay to use `META_CONCEPT` instead if redefining it? Or do you want to make the definitions of the meta library independent of the ones in ranges?
* Do you have a better name for `CPP_CXX_CONCEPT`? Or …

use modern concept definition

---

doc/index.md
include/range/v3/range_fwd.hpp
include/range/v3/view.hpp
include/range/v3/view/trim.hpp
test/view/CMakeLists.txt
test/view/trim.cpp

I hope this is within scope. I thought I'd try getting this in so that it's available for the broader public rather than stuffing it in a library of mine. I'm looking forward to the review comments.
The current implementation is simple thanks to the bidirectional range requirement. Looking at #1112, it should be possible to do with a forward range. But I believe it'd be simpler to add a complementing `drop_last_while` and implement `view::trim` in terms of it and `drop_while`. This possibility makes me wonder if this is okay as is.

Add trim view

---

include/range/v3/detail/config.hpp
include/range/v3/range/access.hpp
test/test_utils.hpp

The first commit makes the test suite build with gcc9 (independent of `-fconcepts`). I think the changes *shouldn't* be necessary and that it is probably a GCC bug, but it only affects test suite code and not library code.
The second commit is a workaround for #1164. Note that although the example in #1164 seems rather trivial, the issue was not detected by the test suite. One should maybe create a test case, but I thought it was more important to get a fix in now since we have a bunch of other ICEs in GCC9 that we can't tackle without #1164 being out of the way.
P.S: I thought about creating a MACRO for the workaround, but since it involves code inside the other macros, it would involve more code than necessary. I can still change this or replace the alias template entirely with the …

Make v1.0-branch build with GCC9

---

cmake/ranges_flags.cmake

The GCC documentation says that unrecognized warning options in the `-Wno-*` form do not cause errors unless other diagnostics are issued. And thus unsupported flags may be appended. This results in a failed
build when there are some false positive warnings.
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

Improve check of -Wno-* compiler flags

---

include/range/v3/to_container.hpp

…claration
MSVC 2019:
1>\range\v3\to_container.hpp(76,1): warning C4459:  declaration of 'size' hides global declaration
1>\range-v3\include\range\v3\to_container.hpp(76,1): warning C4459:                     auto const size = ranges::size(rng);
1>\range\v3\size.hpp(112,13): message :  see declaration of 'ranges::v3::CPOs::size'
1>\range\v3\size.hpp(112,13): message :             RANGES_INLINE_VARIABLE(_size_::fn, size)

Fix to_container.hpp:declaration of 'size' hides global declaration

---

include/range/v3/detail/variant.hpp

Related: #939
Fixes variant.hpp(706,1): warning C4459:  declaration of 'data' hides global declaration on MSVC 2019 /W4
1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459:  declaration of 'data' hides global declaration
1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459:         {
1> \range-v3\include\range\v3\detail\variant.hpp(706,1): warning C4459: ^
1> \range-v3\include\range\v3\data.hpp(84,13): message :  see declaration of 'ranges::v3::CPOs::data'
1> \range-v3\include\range\v3\data.hpp(84,13): message :             RANGES_INLINE_VARIABLE(data_detail::data_fn, data)
1> \range-v3\include\range\v3\data.hpp(84,13): message :             ^

Fix shadow variable warnings in variant.hpp

---

include/range/v3/view/iota.hpp

The changes in c9d18a1e405c8d588859c430951eefb5fe5ae1f0 made iota hard fail for us, because it could not find an appropriate overload for some of our types (that do model the respective concepts). I think the overload below was just too strict by requiring SizedSentinel.

[FIX] iota-distance computation too strict

---

doc/index.md

It is not clear, why we must specify `value_type`. Explanation added.

Small change to basic_iterator documentation.

---

doc/index.md

By the way, why `empty()` is needed? `equal()` could accept sentinel instead...

More detailed view_adaptor doc

---

include/meta/meta_fwd.hpp
include/range/v3/range_fwd.hpp
include/range/v3/utility/box.hpp

Compilers' `is_trivial` intrinsics are not to be trusted (https://godbolt.org/z/8n_4OA).
Fixes #1196.

Implement detail::is_trivial

---

include/range/v3/functional/reference_wrapper.hpp
include/range/v3/iterator/basic_iterator.hpp
include/range/v3/iterator/insert_iterators.hpp
include/range/v3/range/primitives.hpp
include/range/v3/utility/addressof.hpp
include/range/v3/utility/optional.hpp
include/range/v3/view/addressof.hpp
include/range/v3/view/any_view.hpp
include/range/v3/view/partial_sum.hpp
include/range/v3/view/ref.hpp
include/range/v3/view/single.hpp
test/constexpr_core.cpp

I'm going on the principle here that it's more important for `constexpr` to work than to handle overloaded unary `operator&()`. This fixes #1167 
If you all disagree, I can instead do something like:
```cpp
#ifdef __cpp_lib_address_constexpr
#define RANGES_ADDRESSOF_CONSTEXPR constexpr
#else
#define RANGES_ADDRESSOF_CONSTEXPR
#endif
```
and changes all the appropriate functions from `constexpr` to `RANGES_ADDRESSOF_CONSTEXPR`.

Adding a constexpr addressof to fix #1167.

---

include/range/v3/detail/config.hpp
include/range/v3/iterator/access.hpp
include/range/v3/range/access.hpp
include/range/v3/range/primitives.hpp
include/range/v3/utility/any.hpp
include/range/v3/view/stride.hpp
test/view/span.cpp

* VSO#934330 will be fixed in VS2019 16.3
* Despite that VSO#620035 was fixed in VS2019 16.0, the workarounds are still needed; I overreduced the repro. These workarounds are now tagged with the fresh new bug number VSO#895622.
* Remove workarounds for VS2017 bugs, which is no longer supported.

Update MSVC workaround database:

---

BUILD.bazel

The commit abf16a6c6a1919cacc25645588922b1cebe9c879 added new headers to include/std, but these were not exposed in Bazel rules and caused the builds to break.

Add include/std/* to the list of headers available through bazel rules

---

CMakeLists.txt
conanfile.py

Fixes #1212 
Changes:
- conanfile.py: Fix typo: `package_info` -> `package_id`. `package_info(self)` is for settings things like compiler flags and options, whereas `package_id(self)` is for determining package compatibility.
- CMakeLists.txt: `write_basic_package_version_file` has a hidden architecture check. Disable it via the workaround of unsetting `CMAKE_SIZEOF_VOID_P`, at least until an upgrade to CMake 3.14 is reasonable.

Make conan package always compatible

---

CMakeLists.txt
conanfile.py
test_package/CMakeLists.txt

— Remove `settings` property, `build_policy = "missing"`, `build()` and `package_info()` methods, add `no_copy_source` as per https://docs.conan.io/en/latest/howtos/header_only.html
— Fix CMake install pattern to include modulemap/std headers that don't have an extension
— Fix test_package compilation

Conan recipe/packaging fixes

---

.vscode/settings.json
example/calendar.cpp
include/range/v3/detail/config.hpp
include/range/v3/range/conversion.hpp
include/range/v3/view/interface.hpp
test/action/adjacent_remove_if.cpp
test/action/drop.cpp
test/action/drop_while.cpp
test/action/remove_if.cpp
test/action/reverse.cpp
test/action/shuffle.cpp
test/action/slice.cpp
test/action/sort.cpp
test/action/split.cpp
test/action/stable_sort.cpp
test/action/stride.cpp
test/action/take.cpp
test/action/take_while.cpp
test/action/transform.cpp
test/action/unique.cpp
test/algorithm/sort.cpp
test/range/conversion.cpp
test/view/chunk.cpp
test/view/conversion.cpp
test/view/drop.cpp
test/view/intersperse.cpp
test/view/join.cpp
test/view/sliding.cpp

Also, extend `ranges::to` to handle conversions from range-of-range to container-of-container.

Deprecate view->container conversions

---

test/range/conversion.cpp
test/view/conversion.cpp
test/view/drop.cpp

...in tests triggered by #1238. Conversions to nested containers use `view_interface`'s now-deprecated conversion operator templates, triggering deprecation warnings. CI didn't catch this problem because the test cases all use standard containers, which are defined in system headers, for which clang and GCC don't emit warnings.

Workaround deprecation warnings

---

include/concepts/swap.hpp
include/range/v3/range/conversion.hpp
include/std/detail/associated_types.hpp

* React to future changes to MSVC's implementation of `iterator_traits` in `std/detail/associated_types.hpp`
* Use correct bug number for the `concepts::swap` workaround
Drive-by: Remove extraneous parens in the definition of concept `detail::ConvertibletoContainerContainerImpl`

MSVC update:

---

include/range/v3/view/drop.hpp
include/range/v3/view/drop_while.hpp
include/range/v3/view/map.hpp
include/range/v3/view/take_while.hpp

The following are added to namespace cpp20:
* `take_while_view`
* `drop_view`
* `drop_while_view`
* `keys`
* `values`
The following are not added:
* `elements_view` (doesn't appear to exist)
* `istream_view` (will file NB comment to have `basic_istream_view` renamed to `istream_view`)

includes new C++20 range adaptors in namespace cpp20

---

include/range/v3/action/push_back.hpp
include/range/v3/action/push_front.hpp
include/range/v3/action/shuffle.hpp
include/range/v3/action/sort.hpp
include/range/v3/detail/config.hpp
include/range/v3/view/join.hpp
include/range/v3/view/sample.hpp
include/std/detail/associated_types.hpp

... which are only fixed in c++latest or with /experimental:newLambdaProcessor
Drive-by:
* Optimize the metaprogramming in `<std/detail/associated_types.hpp>` for MSVC by using the `std` type traits directly (since they're mostly implemented in the compiler)
* Don't wrap lambdas in `bind_back` when we can use them directly.
* In `<action/sort.hpp>`, don't repeat typenames in predicate and projection default arguments.

Workaround fixed MSVC lambda bugs

---

CMakeLists.txt
cmake/ranges_env.cmake
cmake/ranges_flags.cmake
include/range/v3/detail/config.hpp
test_package/CMakeLists.txt

* export `/permissive- /experimental:preprocessor` as required flags in the cmake config
* Yell in `config.hpp` if we see old MSVC, C++14 mode, or the old preprocessor.

Try to reduce issue reports from MSVC users

---

include/range/v3/functional/not_fn.hpp
include/range/v3/view/drop_while.hpp
include/range/v3/view/take_while.hpp
include/range/v3/view/transform.hpp

This PR applies `RANGES_NO_UNIQUE_ADDRESS` to functions/predicates in 
- transform, take_while, drop_while views
- `logical_negate`
The latter allows EBO out empty predicates in `filter_view`.

Apply [[no_unique_address]] to predicates

---

doc/index.md

Drive-by fix: replace <=> with &harr; to avoid confusion with C++20 spaceship operator.

Fix punctuation and markup in index.md

---

include/range/v3/view/common.hpp

The cpp20 version of view::common is supposed to preserve the underlying range if that is already common, but currently it fails hard if the input is already common:
https://godbolt.org/z/H3LrVw
(the non-cpp20 version works and is unaffected by this PR).

[FIX] cpp20::views::common with common input

---

include/range/v3/range/operations.hpp

Use forwarding_range_ to make the range operations (front, back, etc) safer

---

include/range/v3/iterator/concepts.hpp
include/range/v3/view/tail.hpp

... in `view/tail.hpp`.
Fixes #1326.

Parenthesize non-primary expressions in requires-clauses

---

CMakeLists.txt
cmake/range-v3-config.cmake

The old targets without namespace are kept in an additional targets file
for compatibility reasons.
Addresses issue #1342.

Export CMake targets into range-v3:: namespace

---

include/range/v3/functional/concepts.hpp

gcc10 complained about this.
Introduced in https://github.com/ericniebler/range-v3/blame/121dad313e05aaa88b2839b0244172b0f7065ac3/include/range/v3/functional/concepts.hpp#L75

use missing template argument in concepts

---

cmake/ranges_flags.cmake
include/range/v3/view/adjacent_filter.hpp

Removing 2 warnings with gcc 6.2.0
`include/range/v3/view/adjacent_filter.hpp:97:26: error: declaration of 'prev' shadows a member of 'ranges::adjacent_filter_view<Rng, Pred>::adaptor<Const>' [-Werror=shadow]`

Fix warning about shadowing in adjacent_filter

---

CMakeLists.txt
cmake/range-v3-config.cmake

Fixes the issues raised in https://github.com/ericniebler/range-v3/pull/1343#issuecomment-546168253.
This breaks users who directly link against `meta` and `concepts`, which are now required to be prefixed with `range-v3::`. `range-v3` is available in both forms and thus should reduce the area of user breakage.
Now the `range-v3::` prefixed targets are also available for builds using a non-installed range-v3 CMake buildsystem. This means that targets linking against a range-v3 library won't find inconsistencies due to missing target names whether they're installed or local.

Require prefixing range-v3:: to targets with high chance of clashing

---

include/range/v3/iterator/stream_iterators.hpp

coerce the value written through ostream_iterator to the right type

---

include/range/v3/iterator/concepts.hpp

There is already a workaround for this compiler bug in the definition of `iter_reference_t`. We can leverage that workaround by defining the concept `readable` exclusively in terms of that.

Workaround msvc #683388 in concept readable

---

include/range/v3/range/dangling.hpp

Missed by #1370. A more complete PR would excise `forwarding_range_`.

Make safe_iterator_t standard conformant

---

doc/Doxyfile.in

The path to your build directory is exposed in a URL of the [Examples][1] page. The patch fixes this minor issue, and so the page will be named as `md_examples.html`. If you think to add a redirect from the previous URL, it is possible to create a symbolic link to the new file name.
For predictable and reproducible builds it is important to eliminate all environment details from package data. Particularly, this is about Debian package [librange-v3-doc][2].
[1]: https://ericniebler.github.io/range-v3/md___users_eniebler__code_range-v3_doc_examples.html
[2]: https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/range-v3.html

Strip build path in generated docs

---

include/range/v3/range/concepts.hpp
include/range/v3/range/operations.hpp
include/range/v3/view/all.hpp
include/range/v3/view/drop.hpp
include/range/v3/view/drop_exactly.hpp
include/range/v3/view/slice.hpp
include/range/v3/view/subrange.hpp
include/range/v3/view/take_exactly.hpp

* fold `range_impl_` concept back into `range`
* Replace `forwarding_range_` concept with `safe_range`
Drive-by:
* Remove unused `#define CPP_noop`
* Use `view<uncvref_t<T>>` instead of `view<decay_t<T>>` in the definition of `viewable_range` since pointers cannot model `view`. (Per the editorialish change I submitted in https://github.com/cplusplus/draft/pull/3563).

Finish implementation of P1870R1

---

test/simple_test.hpp
test/test_utils.hpp

It's difficult to test things in ranges - when a check fails, it doesn't actually point back to the test, just points to the testing internals. This PR propagates the source information so that the test output looks like:
```
> ERROR: CHECK failed "(T &&) actual == (U &&) expected"
>       ../test/view/group_by.cpp(94)
>       EXPECTED: 8
>       ACTUAL: 7
```
instead of:
```
> ERROR: CHECK failed "(T &&) actual == (U &&) expected"
>       ../test/view/../test_utils.hpp(43)
>       EXPECTED: 8
>       ACTUAL: 7
```
It'd be nicer to actually have the error contain line 94 of group_by.cpp instead of something not particularly valuable for the tester - but at least this way I can find the right line.

Add source_location to unit tests.

---

cmake/range-v3-config.cmake

> I didn't consider the minimum required version when making the change. The [patch notes for 3.11](https://cmake.org/cmake/help/latest/release/3.11.html#commands) says that `target_link_libraries()` was added then. @marehr, could you open a PR, please?
See #1411

Support cmake version less than 3.11 when installing targets (#1411)

---

include/range/v3/utility/memory.hpp

Fixes gcc10 error `-Werror=type-limits`:
```
In file included from /opt/gcc/gcc-git/include/c++/10.0.1/cassert:44,
from /range-v3/include/range/v3/detail/config.hpp:62,
from /range-v3/include/range/v3/range_fwd.hpp:24,
from /range-v3/include/range/v3/iterator/common_iterator.hpp:25,
from /range-v3/include/range/v3/core.hpp:17,
from /range-v3/test/algorithm/inplace_merge.cpp:23:
/range-v3/include/range/v3/utility/memory.hpp: In instantiation of ‘std::pair<_Tp*, long int> ranges::detail::get_temporary_buffer_impl(std::size_t) [with T = int; std::size_t = long unsigned int]’:
/range-v3/include/range/v3/utility/memory.hpp:74:56:   required from ‘std::pair<_Tp*, long int> ranges::detail::get_temporary_buffer(D) [with T = int; D = long int]’ …
```

fix gcc10 `-Werror=type-limits`

---

include/range/v3/utility/common_tuple.hpp
test/utility/common_type.cpp
test/view/cartesian_product.cpp

Ditto for `common_pair`. Fixes #1422

common reference/type of common_tuple now yields common_tuple, not std::tuple

---

include/concepts/concepts.hpp

Work around compiler bug in msvc 14.25; fixes #1453

---

.vscode/settings.json
include/concepts/concepts.hpp
include/range/v3/iterator/concepts.hpp
include/range/v3/range/access.hpp
include/range/v3/range/concepts.hpp
test/debug_view.hpp
test/utility/concepts.cpp

This is to more closely harmonize range-v3 with C++20's `std::ranges`. Refers to cplusplus/nbballot#278

Remove the enable_view heuristic

---

include/range/v3/view/drop_while.hpp
test/view/drop_while.cpp

I've requested a DR against the CD saying:
> Because it has to compute its `begin()`, it can never model `sized_range` due to not meeting its non-amortized O(1) requirement.

Explicitly opt drop_while_view out of sized_range

---

cmake/ranges_flags.cmake
include/concepts/concepts.hpp
include/concepts/swap.hpp
include/range/v3/detail/config.hpp

* Don't build with the clang-cl flag `-fno-ms-compatibility` for now.
* VSO-573728 was fixed for 16.3
* VSO-654601 workaround is actually for VSO-784772 (What I thought was a regression was actually a distinct bug hidden behind the old workaround.)
* VSO-779708 was fixed for 16.5
* Workarounds for VSO-780775 were removed; there's no reason to keep the macro around.
* VSO-895622 was fixed for 16.6

MSVC bug workaround updates:

---

include/range/v3/view.hpp

Using a `#include <range/v3/all.hpp>` was not providing `views::remove`.

Add a missing `#include <range/v3/view/remove.hpp>`

---

include/concepts/concepts.hpp
include/range/v3/utility/common_tuple.hpp

https://eel.is/c++draft/concept.assignable
I noticed with this code that the current implementation of `concepts::assignable_from` is not the same as the one from the standard.
```c++
#include <concepts/concepts.hpp>
template <class LHS, class RHS>
concept assignable_from =
// ::concepts::common_reference_with<std::remove_reference_t<LHS> const &, std::remove_reference_t<RHS> const&> &&
::concepts::assignable_from<LHS, RHS>;
int main() {
using int_simd [[gnu::vector_size(sizeof(int) * 1)]] = int;
using uint_simd [[gnu::vector_size(sizeof(unsigned) * 1)]] = unsigned;
//   int_simd a = uint_simd{};
static_assert(::concepts::common_reference_with<std::remove_reference_t<int> const &, std::remove_reference_t<unsigned> const&>);
static_assert(!::concepts::common_reference_with<std::remove_refer …
```

assignable_from: use the definition from the C++20 standard

---

include/concepts/concepts.hpp

totally_ordered[_with] and three_way_comparable[_with] depend on
partially-ordered-with. This commit adds the implementation detail and
updates totally_ordered[_with].

adds partially-ordered-with

---

include/range/v3/detail/config.hpp

Workarounds for this bug avoid triggering another bug in 16.6 that seems to be fixed in 16.7 Preview. I validated that everything worked in 16.6, so "another bug" must be triggered by changes since e9fde778be5354cec403afc59d0f026c9fb66cd5. :shrug:

MSVC: enable workarounds for VSO-895622 in VS 2019 v 16.6

---

include/range/v3/experimental/utility/generator.hpp

Preliminary testing shows that range-v3 experimental coroutines does work with GCC 10.1.0 - but it bails on 
`/usr/include/range/v3/experimental/utility/generator.hpp: In copy constructor 'ranges::experimental::coroutine_owner<Promise>::coroutine_owner(const ranges::experimental::coroutine_owner<Promise>&)':
/usr/include/range/v3/experimental/utility/generator.hpp:136:71: error: no matching function for call to 'std::atomic<bool>::store(bool, const
std::memory_order&) const'
136 |                     that.copied_.store(true, std::memory_order_relaxed);
|                                                                       ^
`
Currently `__cpp_coroutines` does not seem to be defined by GCC 10.1.0 (with `-fcoroutines`) but it does define `__cpp_impl_coroutine` and `__cpp_lib_coroutine`. …

Fix coroutine_owner _copied needing to be mutable

---

CMakeLists.txt

Fixed installation on other than Ubuntu GNU/Linux distributions.
Fedora and other GNU/Linux distributions use different $libdir prefixes. Now it can be installed on any GNU/Linux distributions.

Fixed installation on other than Ubuntu distributions

---

README.md

As per https://github.com/ericniebler/range-v3/pull/1554 I moved the `build2` package definition (and build) into another repository which will be handled by the `build2` community: https://github.com/build2-packaging/range-v3
That repository can also be used to develop `range-v3` itself, it's not much different than having the files here. Most users might use it for building revisions which are not parts of a release.
Using that repository, I published `range-v3` `v0.11.0` (matching the tag in this repository). This package and all the future packages will be available there: https://cppget.org/range-v3/0.11.0
I will make sure the future released get published too.
Meanwhile, this PR just adds instruction for using the package in `build2` projects. It also points to the instruction to …

build2 support: Added instructions for build2 users.

---

include/range/v3/detail/config.hpp
include/range/v3/range/access.hpp
include/range/v3/range/concepts.hpp

While compiling the latest `master` with MSVC and C++17 the same warning shows over and over:
```
...
[build] [14/483   0% :: 4.966] Building CXX object test\algorithm\CMakeFiles\range.v3.alg.for_each_n.dir\for_each_n.cpp.obj
[build] The contents of <span> are available only with C++20 or later.
[build] [15/483   0% :: 5.069] Building CXX object test\algorithm\CMakeFiles\range.v3.alg.generate.dir\generate.cpp.obj
[build] The contents of <span> are available only with C++20 or later.
[build] [16/483   0% :: 5.826] Building CXX object test\algorithm\CMakeFiles\range.v3.alg.make_heap.dir\make_heap.cpp.obj
[build] The contents of <span> are available only with C++20 or later.
[build] [17/483   0% :: 6.051] Building CXX object test\algorithm\CMakeFiles\range.v3.alg.max_element.dir\max_element.c …
```

Avoid including empty <span> header when using MSVC and C++17

---

include/concepts/compare.hpp
include/range/v3/compare.hpp
include/range/v3/functional/comparisons.hpp
include/range/v3/range_fwd.hpp
test/utility/compare.cpp
test/utility/concepts.cpp

Fortunately, the Apple clang 12.0.0 from the latest stable version of Xcode 12.0 supports the three-way comparison now, but unfortunately, it still has no concepts.
That leads to build error (Github CI run [github.com/23rd/range-v3/runs/1137532483](https://github.com/23rd/range-v3/runs/1137532483)).
So this PR adds a workaround for the Apple clang.
Related PR: #1508.

Disabled three_way_comparable[_with] concepts when no C++20 concepts.

---

include/range/v3/view/zip_with.hpp
test/view/zip.cpp

Currently, `zip_with(f)` is hardcoded to yield `empty_view<tuple<>>` but it should really be based on the callable itself. This fixes `zip_with([]{ return 42; })` to provide `empty_view<int>` instead.

zip_with on no ranges should derive its value_type from the callable.

---

cmake/coro_test_code.cpp

The CMake coroutine-detection test fails for recent versions of Clang
because `present::promis_type::final_suspend` wasn't `noexcept`.

adds `noexcept` to coro detection `final_suspend`

---

cmake/range-v3-config.cmake

Full description in issue #1621. CMakeLists.txt to reproduse bug and check fix is:
```
cmake_minimum_required(VERSION 3.5)
project(testCmake)
add_subdirectory(range-v3)
list(APPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_SOURCE_DIR}/range-v3)
find_package(range-v3 REQUIRED)
add_executable(${PROJECT_NAME} "main.cc")
target_link_libraries(${PROJECT_NAME} range-v3::range-v3)
target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_14)
```

CMake: Fix find_package and_add subdirectory. Fixes #1621

---

include/range/v3/view/empty.hpp

The following code triggers a CLANGTIDY lint:
```
return ranges::views::empty<int64_t>();
```
> is deprecated Replace views::empty<T>() with views::empty<>. It is now a variable template.
If I do as the lint suggests, I get a template error:
```
return ranges::views::empty<>;
```
> error: too few template arguments for variable template 'empty'
I suspect we actually want the lint message to be:
> is deprecated Replace views::empty<T>() with views::empty<**T**>. It is now a variable template.

Update deprecation message

---

include/range/v3/view/cache1.hpp

For #1603: Undefined behavior caught by GCC 9 on Ubuntu 20.04 when using `views::cache1`
Ensure that cache1's dirty_ member is initialized to avoid UB found by
UBSan:
range-v3-0.11.0/include/range/v3/view/cache1.hpp:35:12: runtime error: load of value 39, which is not a valid value for type 'bool'

Fix read of uninitialized bool in cache1

---

include/range/v3/view/drop_last.hpp
test/view/drop_last.cpp

The documentation states:
> Given a source range and an integral count, return a range consisting of all but the last count elements from the source range, or an empty range if it has fewer elements. 
But there's currently an assert that prevents the empty range case from working.

Removing bogus assert in drop_last.

---

include/range/v3/range/access.hpp
test/range/access.cpp

Follow up of https://github.com/ericniebler/range-v3/pull/1609

accommodate libgcc-9's unusual value for the __cpp_lib_string_view feature test macro - part 2

---

include/range/v3/algorithm/sort.hpp

Fixes C4459 warning produced on msvc toolchain, fixes #939

Fixed msvc W4 C4459 warning

---

CMakeLists.txt

When using CUDA ( nvcc ) with MSVC the `permissive-` flags gets propagated to nvcc when building CUDA files. This causes a failure as `nvcc` doesn't support that command line option. What we need is state this flag should be propagated to the host compiler instead.

Propagate correct compiler flags when using ranges-v3 with CUDA

---

include/range/v3/iterator/concepts.hpp
include/range/v3/view/interface.hpp

There are two fixes in the pull request:
1. Optionally suppress range stream printing #1585 
2. Relax weakly_incrementable concept #1645

Fixing Issues #1585 & #1645

---

include/range/v3/algorithm/aux_/upper_bound_n.hpp

Fixes ericniebler/range-v3#1631
upper_bound and lower bound were both implemented with references.
lower_bound retains that design, whereas upper_bound was changed to
pointers in commit 5b8594dcd41a781d0490cf1ea8d555782cea0cd8.
That looks like a mistake, which this commit undoes.

Allow upper_bound to work in the presence operator &

---

include/range/v3/algorithm/unstable_remove_if.hpp
test/action/unstable_remove_if.cpp

There are cases where unstable_remove_if can call the predicate on the converged-upon "partition element" twice:
https://godbolt.org/z/a8W5oWr3T
It should have the same guarantee as remove_if:
https://en.cppreference.com/w/cpp/algorithm/remove
> Complexity
> Exactly std::distance(first, last) applications of the predicate.
https://en.cppreference.com/w/cpp/algorithm/ranges/remove
> Complexity
> Exactly N applications of the corresponding predicate and any projection, where N = (last - first), and N-1 move operations at worst.

Ensure unstable_remove_if calls the predicate exactly once per element

---

.github/workflows/range-v3-ci.yml

Ubuntu 16.04 LTS virtual environment was removed from GitHub Actions on September 20, 2021
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/

Move CI from Ubuntu 16.04 to 18.04

---

include/range/v3/algorithm.hpp
include/range/v3/algorithm/fold.hpp
include/range/v3/algorithm/fold_left.hpp
include/range/v3/algorithm/fold_right.hpp
test/algorithm/fold.cpp

Per LEWG telecon, renaming `foldl`/`foldr` to `fold_left`/`fold_right` and the `*1` suffix to `_first` for the left fold and `_last` for the right fold. Names not finalized yet, but seem more likely to be the final names than `foldl`/`foldl1`/`foldr`/`foldr1`.
Also removing the projections. First, they were implemented incorrectly anyway. Second, for the variants with no initial value, the projection doesn't really work. This is explained in P2322R5 (see [here](https://isocpp.org/files/papers/P2322R5.html#no-projections) until that one is published).

Updated fold to P2322R5 (no projections, rename)

---

cmake/ranges_env.cmake

Ran into the issue of trying to build without documentation but cmake still failed. The problem in my case is that `doxygen` is present, but `dot` is to be missing from the build environment. This makes `find_package(Doxygen)` fail because cmake treats it as a required component by default: https://cmake.org/cmake/help/v3.23/module/FindDoxygen.html

Only find doxygen if building the docs

---

include/meta/meta.hpp

C++20 [basic.scope.class]: A name N used in a class S shall refer to the
same declaration in its context and when re-evaluated in the completed scope
of S. No diagnostic is required for a violation of this rule.
This rule is violated by the unqualified use of meta::invoke followed by the
declaration of partition_<Fn>::invoke.

Fix name meaning change in nested class

---

.github/workflows/range-v3-ci.yml
include/range/v3/range/conversion.hpp
test/range/conversion.cpp

The current overload set is inconsistent:
```cpp
std::vector<std::pair<int, int>> v = {{1, 2}, {3, 4}};
auto m1 = ranges::to<std::map<int, int>>(v); // ok
auto m2 = v | ranges::to<std::map<int, int>>(); // ok
auto m3 = ranges::to<std::map>(v); // compile error
auto m4 = v | ranges::to<std::map>(); // ok
```
`m3` fails because the logic here tries to instantiate `std::map<std::pair<int, int>>` (specifically, `Cont<range_value_t<Rng>>`) instead of actually using the existing deduction machinery (which is what the `m4` overload correctly uses).

Fixing ranges::to<std::map>(v)

---

include/range/v3/iterator/reverse_iterator.hpp
test/view/reverse.cpp

`reverse_iterator` doesn't properly forward `value_type`, so in cases where the underlying range's `value_type` is not simply `uncvref_t<reference>`, `views::reverse` will end up destroying that information - which is especially problematic if you're `reverse`ing a `zip` and then do some work that relies on the `value_type` not having reference semantics.

Fixing reverse_iterator's value_type.

---

include/range/v3/view/linear_distribute.hpp
test/view/linear_distribute.cpp

`linear_distribute` has an unexpected behavior for integral values when number of values to be calculated is greater than distance between `from` and `to`. My expectation was similar to `numpy` behavior where calculated values are "evenly" distributed with integral precision.
Expectation: 
```
linear_distribute(0, 10, 20) == linear_distribute(0.0, 10.0, 20) | transform(convert_to<int>{})
```
Current implementation:
```
linear_distribute(0, 3, 7)     = [0, 0,   0, 0,   1, 2,   3]
linear_distribute(0.0, 3.0, 7) = [0, 0.5, 1, 1.5, 2, 2.5, 3]
```
Improved implementation:
```
linear_distribute(0, 3, 7)     = [0, 0,   1, 1,   2, 2,   3]
linear_distribute(0.0, 3.0, 7) = [0, 0.5, 1, 1.5, 2, 2.5, 3]
```

linear_distribute improvement

---

include/range/v3/view/subrange.hpp
test/view/subrange.cpp

Fix subrange::next with unsized subrange

---

CMakeLists.txt
cmake/ranges_options.cmake

IMHO installing a subproject with the main project is undesirable, so this patch addresses this issue.

Don't install Range-v3 when it is used as a subproject

---

include/range/v3/detail/config.hpp

ICE on GCC 10 prerelease has been fixed in GCC 10 release series.

Re-enable no_unique_address on GCC

---

include/concepts/concepts.hpp

There is a `#define Nil` buried in Apple's system headers and it breaks range-v3.

Rename Nil because it conflicts with Apple headers

---

include/range/v3/view/zip_with.hpp
test/view/zip.cpp

The distance between iterators is wrongly calculated when the first zipped range is empty:
```cpp
std::vector<int> a = {1, 2, 3, 4, 5};
std::vector<int> b;
auto z0 = zip(b, a);
auto z1 = zip(a, b);
auto d0 = ranges::distance(ranges::begin(z0), ranges::end(z0));
auto d1 = ranges::distance(ranges::begin(z1), ranges::end(z1));
assert(d0 == 0); // failed d0 == 5
assert(d1 == 0); // pass
```
With MSVC
```cpp
std::vector<int> a = {1, 2, 3, 4, 5};
std::vector<int> b; 
auto v = zip(b, a) | ranges::to_vector; // access violation
```

Fix zip/zip_with distance_to

---

test/view/enumerate.cpp
test/view/span.cpp
test/view/take_last.cpp

Some tests lack a call to `test_result`. In effect, these tests could fail without setting nonzero exit code.

Add missing calls to test_result()

---

include/range/v3/action.hpp
include/range/v3/algorithm.hpp
test/bug-guard.cpp

I checked file listings and compared them to include files (I also checked indirect includes). These two headers where not included by call `#include <range/v3/all.hpp>`
closes #1811

Add missing includes

---

include/range/v3/range/primitives.hpp

Some compilers throw an error when compiling - See : https://github.com/citizenfx/fivem/pull/2763
The easy fix is to add the `#include <string>` as some compilers / environnement are not including it, leading to an `error C2039: 'basic_string' is not a member of 'std'`

Include string class in primitive.hpp

---

.gitignore
MODULE.bazel

According to https://bazel.build/external/overview,
WORKSPACE is the legacy way to manage dependencies in Bazel and the new way is now Bzlmod.

Make range-v3 a Bazel module (Support Bzlmod)

---

include/range/v3/view/any_view.hpp

If a provider of an any_view is built without NDEBUG defined, but a consumer is built with NDEBUG defined (e.g., developing one project but using "release"/installed version of another), the consumer will crash due to ABI-incompatibility in any_ref.
Using "remove the assertion" as a discussion-starter, at least. I'd also understand an argument that some might want the ability to keep this assertion. If that's the case, could do something like [what llvm does](https://llvm.org/docs/ProgrammersManual.html#abi-breaking-checks) to separate ABI-breaking checks from non-ABI-breaking checks. 
Or if we're good with just removing this assertion that works of course (as far as I can tell, it's the only ABI-breaking assertion in range-v3)
Repros on clang with sanitizers, and that's an easily …

Remove ABI-incompatible assertion code in any_view.hpp

---

test/test_utils.hpp

Under [P2266](https://wg21.link/p2266r3) 't' by itself is move-eligible, so we need to obfuscate it to get an lvalue.

Fix for C++23 implicit move

---

README.md

Updated README with conan v2 instructions.

Updated conan installation instructions

---

include/range/v3/utility/any.hpp

This PR resolves a conflict with windows.h where `#define interface STRUCT` causes issues. 
The `interface` struct in `any.hpp` has been renamed to `_interface`.

Fix conflict with windows.h by renaming 'interface' to '_interface'
