ericniebler/range-v3

include/range/v3/algorithm.hpp

Fairly self-explanatory - I assume this omission is unintentional.

Add missing header fill_n.hpp to algorithm.hpp.

---

CMakeLists.txt
README.md
biicode.conf
ignore.bii

Note there's no travis deployment. I don't want to pollute your test for something that you have to modify  anyway. Use the `.travis.yml` from Meta as a template, it should be exactly the same. Ask me if you have any doubts.

biicode support

---

include/range/v3/action/concepts.hpp
include/range/v3/action/drop.hpp
include/range/v3/action/drop_while.hpp
include/range/v3/action/erase.hpp
include/range/v3/action/insert.hpp
include/range/v3/action/push_back.hpp
include/range/v3/action/push_front.hpp
include/range/v3/action/remove_if.hpp
include/range/v3/action/slice.hpp
include/range/v3/action/sort.hpp
include/range/v3/action/stable_sort.hpp
include/range/v3/action/stride.hpp
include/range/v3/action/take.hpp
include/range/v3/action/take_while.hpp
include/range/v3/action/transform.hpp
include/range/v3/action/unique.hpp
include/range/v3/algorithm/random_shuffle.hpp
include/range/v3/algorithm/shuffle.hpp
include/range/v3/range_access.hpp
include/range/v3/range_concepts.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/functional.hpp
include/range/v3/utility/iterator_concepts.hpp
include/range/v3/view/iota.hpp
test/utility/concepts.cpp

Try to fix concepts for unmovable (immobile?) types

---

include/range/v3/algorithm.hpp

algorithm.hpp should include is_sorted, is_sorted_until, and minmax_element.

Add missing headers to algorithm.hpp.

---

include/range/v3/utility/variant.hpp
test/view/remove_if.cpp

SFINAE's apply_visitor since under C++14 consexpr it must be "turtles all the way down" with decltype.

fix: variant apply visitor under c++14

---

test/utility/basic_iterator.cpp

d is intentionally set-but-not-used.

Warning fix in test/utility/basic_iterator.cpp

---

include/range/v3/action/concepts.hpp
include/range/v3/action/insert.hpp
include/range/v3/to_container.hpp
test/action/insert.cpp
test/to_container.cpp

* Implement concepts Reservable, RandomAccessReservable, ReserveAndAssign to identify containers that can reserve capacity.
* Use RandomAccessReservable in insert.
* Use ReserveAndAssignable in to_container.

Reservation support (Was #150)

---

include/range/v3/action.hpp
include/range/v3/action/shuffle.hpp
test/action/CMakeLists.txt
test/action/shuffle.cpp

In my opinion, since there is a sort action, there should also be a shuffle action. Requesting review.

Add shuffle action.

---

test/distance.cpp

This PR adds `distance_compare` testcase for "maybe" infinite ranges (which are actually finite).

Add distance_compare test for "maybe" infinite ranges.

---

include/range/v3/numeric/accumulate.hpp
include/range/v3/numeric/inner_product.hpp
include/range/v3/numeric/partial_sum.hpp
include/range/v3/range.hpp
include/range/v3/utility/common_tuple.hpp
include/range/v3/utility/concepts.hpp

Remove breakage of Assignable introduced in the decomposition patch.

---

include/range/v3/range_fwd.hpp
include/range/v3/view/generate.hpp
include/range/v3/view/generate_n.hpp
include/range/v3/view/transform.hpp

and fix doc typo in range_fwd.hpp

Remove unneeded includes of optional.hpp

---

include/range/v3/view/repeat_n.hpp

Perform the assert in the mem-initializer for n_ instead of the constructor body.

Make repeat_n_view constructor constexpr.

---

include/range/v3/algorithm/permutation.hpp
include/range/v3/utility/basic_iterator.hpp
test/algorithm/copy_backward.cpp
test/algorithm/sort.cpp

Things I noticed in passing while importing algorithms into cmcstl2.

Minor fixes

---

include/range/v3/istream_range.hpp
include/range/v3/utility/optional.hpp
include/range/v3/utility/semiregular.hpp
test/CMakeLists.txt
test/istream_range.cpp

Istream range fix

---

include/range/v3/utility/functional.hpp
test/utility/functional.cpp

Support callables and full variadic predicates in logical_negate

---

include/range/v3/algorithm.hpp
include/range/v3/algorithm/max.hpp
include/range/v3/algorithm/min.hpp
include/range/v3/algorithm/minmax.hpp
test/algorithm/CMakeLists.txt
test/algorithm/max.cpp
test/algorithm/min.cpp
test/algorithm/minmax.cpp

Implement algorithms min, max, and minmax from the Ranges TS.

---

.travis.yml
CMakeLists.txt
include/range/v3/utility/variant.hpp

...so that we can get actual error messages.

Disable the header-checking feature in CMakeLists.txt on Travis

---

include/range/v3/utility/variant.hpp

Drive-by: shut up deprecation warnings in alg.random_shuffle.
Fixes #249.

Use an empty variant for visitation

---

include/range/v3/utility/common_iterator.hpp
include/range/v3/view/set_algorithm.hpp
test/test_utils.hpp
test/utility/swap.cpp
test/view/CMakeLists.txt
test/view/set_difference.cpp
test/view/set_intersection.cpp
test/view/set_symmetric_difference.cpp
test/view/set_union.cpp
test/view/zip.cpp

Implement lazy set algorithms as range views, related to issue #280.

implement lazy set algorithms as range views

---

include/range/v3/detail/config.hpp

I had a crazy idea to **actually run the tests** before pushing this time.

Fence post error in the EBO check. It's been one of those weeks.

---

include/range/v3/utility/tagged_pair.hpp

tagged<Base, Tags...> should be constructible from Base&& and Base const&

---

perf/counted_insertion_sort.cpp
perf/sort_patterns.cpp

Various piddly cleanups in sort_patterns and counted_insertion_sort
EDIT: Removed the configuration-related changes from this PR.

sort_patterns cleanup

---

include/range/v3/utility/iterator.hpp
include/range/v3/view/stride.hpp
test/view/stride.cpp

* BUGFIX: `distance_to` works with non-Bidi iterators
* Minimize atomic operations

view::stride:

---

test/utility/iterator.cpp

I recently uncommented `move_cursor`'s member `distance_to`, suppose I should make sure it keeps working.

Regression test for move_iterator distance.

---

include/range/v3/view/stride.hpp

Works around [GCC PR 71225](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71225)

Use tag dispatch for stride_view::adaptor::clean.

---

include/range/v3/detail/config.hpp
include/range/v3/utility/random.hpp

Fix workaround for lack of thread_local on OSX.

---

include/range/v3/algorithm/shuffle.hpp

Fairly self-explanatory. Performance is equivalent to the "old" implementation when `is_same<S, I>()`, the "old" implementation's best case.

Shuffle: single-pass algorithm

---

include/range/v3/algorithm.hpp
include/range/v3/view.hpp

Add sample/sample_view to the appropriate headers

---

README.md

Since the documentation issues raised in #419 might remain unresolved for a while, this at least provides some pointers for those wanting to learn more about the library.

Add some useful resources to the readme

---

include/range/v3/view/for_each.hpp
include/range/v3/view/single.hpp

Improve error message for misuse of yield().

---

include/range/v3/utility/common_iterator.hpp

common_iterator.hpp defines no views.

Don't include view_facade.hpp in common_iterator.hpp; fixes #468.

---

conanfile.py
test_package/CMakeLists.txt
test_package/conanfile.py
test_package/example.cpp

Hi @ericniebler
I've created a conan package recipe for you. You can test it by:
- Install conan (https://conan.io/downloads)
- Execute ``conan test_package``. It will build the package and run an example I copied from your docs linking with the conan package.
If you want to upload to conan.io:
- Register in conan.io with the **ericniebler** username
- `conan export ericniebler/stable` It register the recipe in the client cache.
- `conan upload range-v3/latest@ericniebler/stable -r conan.io` 
Finally I used "latest" as the package version, because you mention that you are not versioning the releases. Feel free to change username, channel etc.
The files contained in the PR are:
- `conanfile.py`:  Main recipe for you range-v3 library. Just takes the headers and pack them, very easy.
- …

Conan recipe

---

include/range/v3/utility/iterator_concepts.hpp

use lvalue ref to value_type_t in IndirectCallable

---

include/range/v3/view/bounded.hpp
test/view/bounded.cpp

Fully support const & mutable underlying views in view::bounded.

---

.travis.yml

Submitting a PR so that Travis will run. Not sure if this is a valid fix yet.

attempt to fix libc++ build

---

include/range/v3/view/map.hpp
test/view/keys_value.cpp

return prvalues instead of xvalues from get_first & get_second

---

include/range/v3/utility/iterator.hpp
include/range/v3/view.hpp
include/range/v3/view/sliding.hpp
test/simple_test.hpp
test/test_utils.hpp
test/view/CMakeLists.txt
test/view/sliding.cpp

A bit of polish on Tobias's sliding view from #488, rebased onto my `non_propagating_cache` change from #521.

Sliding window

---

include/range/v3/numeric/adjacent_difference.hpp
include/range/v3/numeric/partial_sum.hpp
include/range/v3/utility/invoke.hpp

* adjacent_difference.hpp and partial_sum.hpp need to include algorithm/tagspec.hpp
* invoke.hpp needs to include concepts.hpp
Fixes #548.

header fixes:

---

include/range/v3/view.hpp

Not sure whether the original code is intended, it looks like overlook to me. test plan: Travis-CI

include view/set_algorithm.hpp in view.hpp

---

include/range/v3/view/for_each.hpp
include/range/v3/view/single.hpp

- Use CopyConstructible instead of SemiRegular
- Make the view SemiRegular using "detail::optional"
- closes ericniebler/range-v3#452
- almost closes ericniebler/range-v3#441

Release the constraints on view::single

---

doc/index.md
include/range/v3/view/c_str.hpp
include/range/v3/view/cycle.hpp
include/range/v3/view/filter.hpp
include/range/v3/view/for_each.hpp
include/range/v3/view/sample.hpp

Related to #461, adds missing documentation to some views.

[docs] Fix missing documentation of some views.

---

README.md

Point the AppVeyor badge at ericniebler's AppVeyor.

---

doc/index.md

This adds a list of the available actions to the front-page.

[docs] Document actions in front-page.

---

include/range/v3/view/for_each.hpp
include/range/v3/view/join.hpp
include/range/v3/view/transform.hpp
test/CMakeLists.txt
test/bug566.cpp

Fixes #566, but I am not sure what could be the consequences.

Drop for_each_view, return join(transform(x)) instead

---

include/range/v3/action.hpp
include/range/v3/action/reverse.hpp
test/action/CMakeLists.txt
test/action/reverse.cpp

Implements action::reverse.
Closes #477.

action::reverse

---

.travis.yml

This turns of clang modules temporarily until we fix #607

[travis-ci] disable clang modules

---

.travis.yml

[travis-ci] disables boost

---

include/range/v3/view/empty.hpp
test/span.cpp

view::empty is trivially contiguous

---

.gitignore
include/range/v3/detail/config.hpp
include/range/v3/detail/optional.hpp
include/range/v3/detail/variant.hpp
include/range/v3/size.hpp
include/range/v3/utility/compressed_pair.hpp
include/range/v3/view/chunk.hpp
include/range/v3/view/concat.hpp
include/range/v3/view/join.hpp
include/range/v3/view/reverse.hpp
test/algorithm/next_permutation.cpp
test/algorithm/prev_permutation.cpp
test/test_iterators.hpp
test/test_utils.hpp
test/view/chunk.cpp
test/view/join.cpp
test/view/reverse.cpp
test/view/transform.cpp

Implement chunk_view for input ranges

---

include/range/v3/at.hpp
include/range/v3/view_interface.hpp
test/index.cpp

I've added the relative tests to `index.cpp`. If there was a more appropriate location, please let me know and I'll make the corresponding corrections.

View interface at

---

include/range/v3/view/reverse.hpp

Now that the TS requires references obtained from forward iterators to remain valid for the lifetime of the range, `reverse_view` doesn't need to workaround stashing iterators. More importantly, non-stashing iterators shouldn't pay a performance price to enable stashing iterators to work.

Simplify reverse_view

---

include/range/v3/view/drop.hpp
test/view/drop.cpp

RandomAccessRange\<R\> does not imply RandomAccessRange\<R const\>
Fixes #728.

Fix const bug in drop_view

---

include/range/v3/view/adjacent_filter.hpp
test/view/unique.cpp

* const correctness: don't use `mutable_base`
* EBO the predicate

minor adjacent_filter_view cleanup:

---

include/range/v3/view/intersperse.hpp

* const correctness
* rename `toggl_` to `toggle_`
* Don't impede NRVO with `std::move` in `cursor_adaptor::begin`
* `cursor_adaptor::equal` requires `Sentinel<iterator_t<Rng>, iterator_t<Rng>>`
* simplify `cursor_adaptor::distance_to`
* constexpr and noexcept

minor intersperse_view refactor:

---

include/range/v3/view/indirect.hpp

* const correct `size`
* constexpr / noexcept

indirect_view update

---

include/range/v3/detail/variant.hpp

visiting an out-of-range variant index is UB

---

include/range/v3/detail/variant.hpp

Fix the fix that I fixed before

---

include/range/v3/view/adjacent_filter.hpp
test/view/unique.cpp

... so that mutable-only base views actually work.

unique_view: don't evaluate iterator_t<non-range>

---

install_libcxx.sh

...update TRUNK in install_libcxx.sh to 6.0.0.

clang 5.0.0 has been released

---

include/range/v3/view/chunk.hpp
test/view/chunk.cpp

Fixes https://stackoverflow.com/questions/49210190.

view::chunk should tolerate mutable-only base ranges

---

include/range/v3/begin_end.hpp

Force failure for begin/end on volatile initializer_list

---

include/range/v3/begin_end.hpp

... for 8.2 and trunk; disable our workarounds appropriately.

GCC PR 85765 is fixed

---

test/utility/common_iterator.cpp

... since we no longer support Clang/C2.

Don't workaround clang/c2 in utility.common_iterator

---

include/range/v3/algorithm/inplace_merge.hpp
test/action/stable_sort.cpp
test/algorithm/stable_sort.cpp

...until I can localize the interaction between range-v3 and MSFTL's `_Vector_iterator`.

Nasty hack to unblock fix-reverse-iterator

---

.vscode/c_cpp_properties.json
include/meta/meta.hpp
include/range/v3/detail/config.hpp
include/range/v3/span.hpp
include/range/v3/utility/basic_iterator.hpp
include/range/v3/utility/box.hpp
include/range/v3/utility/compressed_pair.hpp
include/range/v3/utility/invoke.hpp
include/range/v3/utility/tagged_pair.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/sliding.hpp
test/bug474.cpp
test/bug566.cpp
test/test_utils.hpp
test/utility/basic_iterator.cpp
test/view/cartesian_product.cpp

New concepts syntax

---

include/range/v3/detail/variant.hpp
include/range/v3/view/generate.hpp
include/range/v3/view/generate_n.hpp
test/view/generate.cpp
test/view/generate_n.cpp

fixes #819
Includes fixes for #911 and #909.

generate views call the function once per dereferenceable iterator position

---

include/range/v3/view/cycle.hpp
include/range/v3/view/repeat.hpp
test/view/chunk.cpp
test/view/cycle.cpp
test/view/sliding.cpp

fixes #783, fixes #780, fixes #778

Abandon the cyclic iterator experiment as a hopeless bug farm

---

include/range/v3/utility/iterator.hpp
test/utility/iterator.cpp

I'm not sure if I should have constrained `operator=` in some way but in general this should do it.

Implemented ostream_joiner (#868)

---

include/range/v3/span.hpp

Workaround MSVC bug in span.hpp

---

include/range/v3/range_fwd.hpp
include/range/v3/span.hpp
include/range/v3/utility/box.hpp
include/range/v3/utility/common_type.hpp
include/range/v3/utility/concepts.hpp
include/range/v3/utility/tagged_pair.hpp
test/constexpr_core.cpp
test/span.cpp
test/view/indirect.cpp

Implement detail::is_convertible alias template

---

doc/index.md

I have added "Create Custom Iterators" section. It is mainly consists from example code...
Since there is almost no information about basic_iterator, which seems to be the basis of library... Maybe it is better to have at least something.

Added example of RandomAcess iterator.

---

include/range/v3/view/take_while.hpp
test/view/take_while.cpp

This patch enables the example code used in #892

Projection support for view::take_while

---

include/range/v3/view/drop_while.hpp
test/view/drop_while.cpp

... and the next view (#892)
Merry Christmas! :-)

Projection support for view::drop_while

---

cmake/ranges_flags.cmake
include/range/v3/action.hpp
include/range/v3/action/adjacent_remove_if.hpp
include/range/v3/action/remove_if.hpp
include/range/v3/action/stride.hpp
include/range/v3/algorithm.hpp
include/range/v3/algorithm/adjacent_remove_if.hpp
test/action/CMakeLists.txt
test/action/adjacent_remove_if.cpp
test/algorithm/CMakeLists.txt
test/algorithm/adjacent_remove_if.cpp

The adjacent_remove_if algorithm and action are similar to
adjacent_remove_if_view in functionality.

adds adjacent_remove_if algorithm and action (trunk)

---

include/range/v3/view/transform.hpp
test/view/transform.cpp

Make iter_transform2_view const-correct

---

include/range/v3/detail/config.hpp
include/range/v3/utility/common_tuple.hpp
include/std/detail/associated_types.hpp

More MSVC 1.0 work

---

include/range/v3/detail/config.hpp
include/range/v3/utility/semiregular.hpp
include/range/v3/view/adjacent_filter.hpp
include/range/v3/view/cartesian_product.hpp
include/range/v3/view/chunk.hpp
include/range/v3/view/concat.hpp
include/range/v3/view/const.hpp
include/range/v3/view/cycle.hpp
include/range/v3/view/exclusive_scan.hpp
include/range/v3/view/group_by.hpp
include/range/v3/view/indirect.hpp
include/range/v3/view/intersperse.hpp
include/range/v3/view/join.hpp
include/range/v3/view/move.hpp
include/range/v3/view/partial_sum.hpp
include/range/v3/view/sample.hpp
include/range/v3/view/set_algorithm.hpp
include/range/v3/view/sliding.hpp
include/range/v3/view/split.hpp
include/range/v3/view/split_when.hpp
include/range/v3/view/stride.hpp
include/range/v3/view/take.hpp
include/range/v3/view/take_while.hpp
include/range/v3/view/transform.hpp
include/range/v3/view/zip_with.hpp

Even more MSVC 1.0 work

---

include/concepts/concepts.hpp
include/range/v3/algorithm/sample.hpp
include/range/v3/detail/config.hpp
include/range/v3/functional/invoke.hpp
include/range/v3/iterator/concepts.hpp
include/range/v3/iterator/counted_iterator.hpp
include/range/v3/iterator/operations.hpp
include/range/v3/range/concepts.hpp
include/range/v3/utility/move.hpp
include/range/v3/utility/optional.hpp
include/range/v3/view/group_by.hpp
include/range/v3/view/transform.hpp
test/action/split.cpp
test/algorithm/partial_sort_copy.cpp
test/range/access.cpp

MOAR MSVC 1.0 work

---

include/range/v3/view/cartesian_product.hpp
test/view/cartesian_product.cpp

cartesian_product: make traits SFINAE-friendly

---

test/algorithm/copy_backward.cpp
test/algorithm/find.cpp
test/algorithm/find_if.cpp
test/algorithm/is_heap_until.hpp
test/algorithm/is_sorted_until.cpp
test/algorithm/lower_bound.cpp
test/algorithm/partial_sort_copy.cpp
test/algorithm/partition.cpp
test/algorithm/partition_copy.cpp
test/algorithm/remove.cpp
test/algorithm/remove_copy.cpp
test/algorithm/remove_copy_if.cpp
test/algorithm/remove_if.cpp
test/algorithm/replace.cpp
test/algorithm/replace_if.cpp
test/algorithm/rotate.cpp
test/algorithm/rotate_copy.cpp
test/algorithm/search.cpp
test/algorithm/search_n.cpp
test/algorithm/set_difference.hpp
test/algorithm/set_symmetric_difference.hpp
test/algorithm/set_union.hpp
test/algorithm/stable_partition.cpp
test/algorithm/unique.cpp
test/algorithm/unique_copy.cpp
test/algorithm/upper_bound.cpp
test/range/conversion.cpp

Still yet even more MSVC 1.0 work

---

include/range/v3/detail/config.hpp
include/range/v3/range/access.hpp

Final MSVC tweaks

---

include/range/v3/utility/iterator.hpp
test/utility/iterator.cpp

This PR fix https://github.com/ericniebler/range-v3/issues/1110

fix for #1110

---

conanfile.py

Makes it possible to export range-v3. I think it's just BAU to upload to bintray from here.

Added Conan.io version

---

doc/index.md

Short documentation, which describes how to use `view_adaptor`s `mixin`.
For this version https://github.com/ericniebler/range-v3/pull/1099

small documentation for adaptor mixin

---

include/range/v3/view_adaptor.hpp

Simplify adaptor_cursor::mixin metaprogramming

---

CMakeLists.txt

Remove redundant definition of rv3_add_test

---

include/range/v3/view/enumerate.hpp
include/range/v3/view/zip_with.hpp
test/range/conversion.cpp

squash another udt difference type bug, work around clang-8.0 bug

---

include/range/v3/view_interface.hpp
test/view/generate_n.cpp

Implement https://github.com/ericniebler/range-v3/issues/1147

view_interface empty() for SizedRange

---

doc/index.md

Short explanation of view constness and validity.

documentation: view constness

---

include/range/v3/algorithm/sample.hpp

* The sample size should use the difference type of the output range, not the input range.
* Don't use the URBG when the sample size is greater than or equal to the population size.
* Formatting.
* Fix usage of `goto` to avoid [stmt.dcl]/3.

algorithm/sample cleanup:

---

include/range/v3/view/subrange.hpp

Simplify constraint on subrange constructor

---

include/range/v3/view/cartesian_product.hpp
test/view/cartesian_product.cpp

Fix inductive proof of distance between cartesian_product iterators

---

include/range/v3/view/cartesian_product.hpp
test/view/cartesian_product.cpp

Difference types are different after P1522

---

include/range/v3/view/interface.hpp
include/range/v3/view/stride.hpp
test/view/stride.cpp

SCARY the range ostream inserter; friend-ify stride_view::adaptor<!Const>

---

include/range/v3/view/cartesian_product.hpp
test/view/cartesian_product.cpp

Always constify Views in cartesian_product_view::cursor

---

cmake/ranges_env.cmake

...by treating the value numerically only if the string is a sequence of digits.

Fix RANGES_CXX_STD handling in CMakeLists.txt

---

appveyor.yml

...and add license and copyright to appveyor.yml.
This is kind of a stopgap measure as I'm looking at migrating our Windows CI to Azure Pipelines (10 parallel jobs >> 1 parallel job).

Slash appveyor matrix

---

include/range/v3/iterator/access.hpp
include/range/v3/iterator/concepts.hpp

refs ericniebler/stl2#578, refs ericniebler/stl2#514, refs ericniebler/stl2#594

improve readable and indirectly_swappable concepts

---

include/range/v3/detail/config.hpp
include/std/detail/associated_types.hpp
test/bug1335.cpp

Workaround GCC 91923 in detail/associated_types.hpp

---

include/range/v3/algorithm/ends_with.hpp
include/range/v3/algorithm/equal.hpp
include/range/v3/algorithm/find_first_of.hpp
test/algorithm/ends_with.cpp

Issue raised by @CaseyCarter at https://github.com/ericniebler/range-v3/pull/1351#discussion_r336815516.

Fix license version

---

include/range/v3/utility/addressof.hpp

Fix spelling errors

---

include/range/v3/view/drop_last.hpp

A comment still has the repeated requirement.

Remove repeated view_ requirement

---

include/range/v3/view/group_by.hpp
test/view/group_by.cpp

- Can handle initially-false predicate
- Only N-1 predicate invocations

group_by() improvements (fixes #1393)

---

include/range/v3/iterator/concepts.hpp

for compiling Ranges in VxWorks Environment.

Adding Wind River Systems Macro(_IS_WRS)

---

include/range/v3/range/access.hpp
include/range/v3/range/concepts.hpp
include/range/v3/range/conversion.hpp
include/range/v3/utility/common_type.hpp

Remove forward declarations of stdlib entities

---

cmake/range-v3-config.cmake

Thanks also to Johel Ernesto Guerrero Peña <johelegp@gmail.com>

Fix find_package in parent and subdirectory

---

.gitignore
include/range/v3/detail/range_access.hpp
include/range/v3/iterator/basic_iterator.hpp
include/range/v3/view/interface.hpp
test/utility/concepts.cpp
test/view/facade.cpp

add data to view_interface

---

include/range/v3/iterator/concepts.hpp

make _is_integer_like_<__int128> = true, fixes #1514

---

include/range/v3/algorithm/sample.hpp

See i.e. http://eel.is/c++draft/alg.random.sample

ranges::sample is in C++20 already

---

include/range/v3/algorithm/for_each_n.hpp

See i.e. http://eel.is/c++draft/alg.foreach

for_each_n is already in C++20

---

README.md

Update README.md with example how to use Conan package manager to get
Range v3 library.

Add Conan installation instructions

---

include/range/v3/action/transform.hpp
include/range/v3/algorithm/replace.hpp
include/range/v3/algorithm/replace_if.hpp
include/range/v3/algorithm/transform.hpp
include/range/v3/iterator/access.hpp
include/range/v3/iterator/common_iterator.hpp
include/range/v3/iterator/concepts.hpp
include/range/v3/iterator/counted_iterator.hpp
include/range/v3/iterator/move_iterators.hpp
include/range/v3/iterator/traits.hpp
include/range/v3/numeric/partial_sum.hpp
include/range/v3/range_fwd.hpp
include/range/v3/utility/memory.hpp
include/range/v3/view/adaptor.hpp
include/range/v3/view/indirect.hpp
include/range/v3/view/zip.hpp
include/std/detail/associated_types.hpp
include/std/iterator
test/iterator/basic_iterator.cpp
test/iterator/iterator.cpp
test/view/zip.cpp

* adds indirectly_readable_traits
* adds indirectly_readable
* adds indirectly_writable
* deprecates readable_traits
* deprecates readable
* deprecates writable
* replaces all instances of the deprecated versions with the new ones

applies P1878

---

include/range/v3/view/generate.hpp
include/range/v3/view/generate_n.hpp

cast unused generate expression to void to silence -Wunused-result

---

cmake/ranges_flags.cmake

Default RANGES_CXX_STD to 17 when targeting MSVC

---

include/concepts/concepts.hpp

fix #1546: Visibility bug in gcc-9 and below using concepts

---

include/range/v3/range/conversion.hpp
test/range/conversion.cpp

add ranges::to overload for converting to container of containers

---

cmake/ranges_flags.cmake
cmake/ranges_options.cmake

Did not add an option to disable warning checks, only added an option for -Werror

Add an option to disable -Werror. Fixes #1528

---

include/range/v3/functional/on.hpp
test/functional/CMakeLists.txt
test/functional/on.cpp

functional: fix ranges::on

---

doc/index.md

add missing include to documentation

---

include/range/v3/view/join.hpp
test/view/join.cpp

Fixing unconditional noexcept in join of glvalue case

---

test/view/tokenize.cpp

... instead of lying about being bidi.

P2770R0 makes stashing `regex_token_iterator` input
